ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "quietHoursStart" TEXT DEFAULT '20:00';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "quietHoursEnd" TEXT DEFAULT '08:00';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "dailyAutomatedSmsLimit" INTEGER NOT NULL DEFAULT 75;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "leadCooldownHours" INTEGER NOT NULL DEFAULT 18;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "autoPauseFailedSends" BOOLEAN NOT NULL DEFAULT TRUE;
