[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/app"
  to = "/.netlify/functions/protected-page"
  status = 200

[[redirects]]
  from = "/verify-email"
  to = "/.netlify/functions/verify-email"
  status = 200

[[redirects]]
  from = "/oauth/authorize"
  to = "/.netlify/functions/authorize"
  status = 200

[[redirects]]
  from = "/oauth/token"
  to = "/.netlify/functions/oauth-token"
  status = 200

[[redirects]]
  from = "/oauth/userinfo"
  to = "/.netlify/functions/oauth-userinfo"
  status = 200

[[redirects]]
  from = "/oauth/logout"
  to = "/.netlify/functions/oauth-logout"
  status = 200

[[redirects]]
  from = "/.well-known/oauth-authorization-server"
  to = "/.netlify/functions/oauth-well-known"
  status = 200

[[redirects]]
  from = "/.well-known/openid-configuration"
  to = "/.netlify/functions/oauth-well-known"
  status = 200


[[redirects]]
  from = "/.well-known/jwks.json"
  to = "/.netlify/functions/oauth-jwks"
  status = 200
