import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createSkyDexiaMemory } from '../src/index.mjs';
import { createSkyDexiaMemoryMiddleware } from '../platform/skydexia-memory-middleware.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const tmp=await fs.mkdtemp(path.join(os.tmpdir(),'skydexia-memory-smoke-'));
const old=process.cwd();process.chdir(tmp);
const checks=[];function check(name,passed,detail={}){checks.push({name,passed:Boolean(passed),detail});if(!passed)throw new Error('Smoke failed: '+name);}
const local=createSkyDexiaMemory({mode:'local-sidecar',projectId:'smoke-local',storage:{kind:'local-jsonl',rootDir:path.join(tmp,'.skydexia-memory')}});
await local.init();
await local.remember({type:'rule',title:'Preserve existing branding',tags:['branding','ui'],text:'Preserve existing branding, CSS, polish, routes, and working plumbing.'});
const r=await local.recall({query:'branding css polish plumbing',limit:3});
check('local-sidecar recall returns memory',r.count===1&&r.contextText.includes('Preserve existing branding'),{count:r.count});
const inj=await local.inject({target:'AGENTS.md',query:'branding css polish plumbing'});
const agents=await fs.readFile(path.join(tmp,'AGENTS.md'),'utf8');
check('context injection writes AGENTS.md block',inj.inserted&&agents.includes('SKYDEXIA_MEMORY_CONTEXT_BEGIN'),{target:inj.target});
const platform=createSkyDexiaMemoryMiddleware({projectId:'smoke-platform',rootDir:path.join(tmp,'.platform-memory')});
await platform.recordDirective({title:'Directive checkmarks only',complete:true,text:'Directive status uses ✅ and ☐ only.',evidence:{smoke:true}});
await platform.recordSmoke({title:'Platform embedded smoke',passed:true,text:'Platform middleware records smoke proof.',evidence:{passed:true}});
const before=await platform.beforePlan({userRequest:'checkmarks smoke proof directive',memoryLimit:5});
check('platform-embedded recalls directive and smoke proof',before.skydexiaMemoryContext.includes('Directive checkmarks only')&&before.skydexiaMemoryContext.includes('Platform embedded smoke'));
const secret=await local.remember({type:'secret-test',title:'Secret redaction',text:'api_key=sk-1234567890abcdefghijklmnopqrstuvwxyz'});
check('secret redaction is active',!secret.text.includes('sk-1234567890'),{text:secret.text});
const pack=await local.exportPack();
check('export pack includes memories and events',Array.isArray(pack.memories)&&pack.memories.length>=2&&Array.isArray(pack.events),{memories:pack.memories.length});
process.chdir(old);
const proof={version:'6.8.1',status:'PASS',generatedAt:new Date().toISOString(),tmpDir:tmp,claimsVerified:['local-sidecar memory capture','local-sidecar recall','AGENTS.md context injection','platform-embedded middleware recall','directive memory recording','smoke proof memory recording','secret redaction','export pack generation'],checks};
await fs.mkdir(path.join(root,'proof'),{recursive:true});
await fs.writeFile(path.join(root,'proof','SMOKE_PASS_v6.8.1.json'),JSON.stringify(proof,null,2)+'\n');
console.log(JSON.stringify(proof,null,2));
