import assert from 'node:assert/strict';
import { renderApp } from '../src/ui/app.ts';

const html = renderApp();
for (const id of ['load-purpose', 'load-walkthroughs', 'run-truth-validator', 'load-runtime-contracts', 'validate-provider-contract', 'run-readiness', 'list-readiness-runs', 'load-claim-catalog', 'load-claim-evidence', 'export-contract-pack', 'load-strategy-scorecard', 'load-strategy-actions', 'export-strategy-pack', 'load-release-gate', 'load-release-drift', 'export-release-pack', 'load-target-summary', 'load-cutover-summary', 'list-cutover-runs', 'run-cutover', 'export-cutover-pack', 'load-rollback-summary', 'list-rollback-runs', 'run-rollback', 'export-rollback-pack', 'list-target-probes', 'run-target-probe', 'export-target-pack', 'load-proof-matrix', 'load-walkthrough-run', 'load-report-summary', 'generate-report-site', 'export-report-site', 'generate-proof-site', 'run-replay', 'run-article-enrich', 'list-article-enrichments', 'export-article-enrich', 'run-article-review', 'list-article-reviews', 'export-article-review', 'run-article-remediate', 'list-article-remediations', 'export-article-remediate', 'run-publish-execute', 'run-publish-retry', 'run-publish-scheduled', 'export-publish', 'export-visibility', 'export-audit', 'create-auth-key', 'save-agency-settings', 'create-seat', 'create-client', 'export-invoice', 'create-backlink-site', 'queue-backlink-placement', 'reconcile-backlink', 'show-backlink-dashboard', 'export-bundle', 'import-bundle', 'clone-bundle']) {
  assert.equal(html.includes(`id="${id}"`), true, `Missing UI control ${id}`);
}
for (const value of ['option value="wix"', 'option value="ghost"']) {
  assert.equal(html.includes(value), true, `Missing publish platform ${value}`);
}
for (const path of ['/v1/capabilities', '/v1/walkthroughs', '/v1/truth/validate', '/v1/runtime/contracts', '/v1/providers/validate', '/v1/articles/enrichments', '/v1/articles/enrich', '/v1/articles/enrich/export', '/v1/articles/reviews', '/v1/articles/review', '/v1/articles/review/export', '/v1/articles/remediations', '/v1/articles/remediate', '/v1/articles/remediate/export', '/v1/readiness/runs', '/v1/readiness/run', '/v1/claims/catalog', '/v1/claims/evidence', '/v1/contracts/export', '/v1/strategy/scorecard', '/v1/strategy/actions', '/v1/strategy/export', '/v1/release/gate', '/v1/release/drift', '/v1/release/export', '/v1/targets/summary', '/v1/targets/probes', '/v1/targets/probe', '/v1/targets/export', '/v1/cutover/summary', '/v1/cutover/runs', '/v1/cutover/run', '/v1/cutover/export', '/v1/rollback/summary', '/v1/rollback/runs', '/v1/rollback/run', '/v1/rollback/export', '/v1/proof/matrix', '/v1/walkthrough-runs', '/v1/reports/summary', '/v1/reports/site', '/v1/reports/export', '/v1/proof/site', '/v1/visibility/replay', '/v1/publish/execute', '/v1/publish/retry', '/v1/publish/run-scheduled', '/v1/evidence/export', '/v1/auth/keys', '/v1/agency/settings', '/v1/agency/seats', '/v1/agency/clients', '/v1/agency/usage', '/v1/agency/invoices/export', '/v1/backlinks/sites', '/v1/backlinks/placements', '/v1/backlinks/reconcile', '/v1/backlinks/dashboard', '/v1/workspace-bundles/export', '/v1/workspace-bundles/import', '/v1/workspace-bundles/clone']) {
  assert.equal(html.includes(path), true, `Missing UI path ${path}`);
}
console.log(JSON.stringify({ ok: true, checks: ['UI scanner detected live controls for purpose, walkthrough, truth validation, article enrichment, article review, article remediation, Wix/Ghost publishing, and workspace bundle export/import/clone flows and report/proof controls plus readiness, strategy, release-gate, contract-truth, runtime contracts, claim evidence, and proof-site controls plus target-probe controls and cutover controls plus rollback controls'] }, null, 2));
