import assert from 'node:assert/strict';
import fs from 'node:fs';

const indexSource = fs.readFileSync(new URL('../src/index.ts', import.meta.url), 'utf8');
const requiredRoutes = [
  'GET /v1/capabilities',
  'GET /v1/walkthroughs',
  'POST /v1/truth/validate',
  'GET /v1/articles/enrichments',
  'POST /v1/articles/enrich',
  'POST /v1/articles/enrich/export',
  'GET /v1/articles/reviews',
  'POST /v1/articles/review',
  'POST /v1/articles/review/export',
  'GET /v1/articles/remediations',
  'POST /v1/articles/remediate',
  'POST /v1/articles/remediate/export',
  'GET /v1/readiness/runs',
  'POST /v1/readiness/run',
  'GET /v1/claims/catalog',
  'POST /v1/contracts/export',
  'GET /v1/runtime/contracts',
  'POST /v1/providers/validate',
  'GET /v1/claims/evidence',
  'POST /v1/proof/site',
  'GET /v1/strategy/scorecard',
  'GET /v1/strategy/actions',
  'POST /v1/strategy/export',
  'GET /v1/visibility/replays',
  'POST /v1/visibility/replay',
  'GET /v1/visibility/dashboard',
  'POST /v1/publish/execute',
  'POST /v1/publish/retry',
  'POST /v1/publish/run-scheduled',
  'GET /v1/publish/queue',
  'POST /v1/evidence/export',
  'GET /v1/auth/keys',
  'POST /v1/auth/keys',
  'GET /v1/agency/settings',
  'POST /v1/agency/settings',
  'GET /v1/agency/seats',
  'POST /v1/agency/seats',
  'GET /v1/agency/clients',
  'POST /v1/agency/clients',
  'GET /v1/agency/usage',
  'POST /v1/agency/invoices/export',
  'GET /v1/backlinks/sites',
  'POST /v1/backlinks/sites',
  'GET /v1/backlinks/dashboard',
  'POST /v1/backlinks/placements',
  'POST /v1/backlinks/reconcile',
  'POST /v1/workspace-bundles/export',
  'POST /v1/workspace-bundles/import',
  'POST /v1/workspace-bundles/clone',
  'GET /v1/proof/matrix',
  'GET /v1/walkthrough-runs',
  'GET /v1/reports/summary',
  'POST /v1/reports/site',
  'POST /v1/reports/export',
  'GET /v1/release/gate',
  'GET /v1/release/drift',
  'POST /v1/release/export',
  'GET /v1/targets/summary',
  'GET /v1/targets/probes',
  'POST /v1/targets/probe',
  'POST /v1/targets/export',

  'GET /v1/cutover/summary',
  'GET /v1/cutover/runs',
  'POST /v1/cutover/run',
  'POST /v1/cutover/export',
  'GET /v1/rollback/summary',
  'GET /v1/rollback/runs',
  'POST /v1/rollback/run',
  'POST /v1/rollback/export',
];
for (const route of requiredRoutes) assert.equal(indexSource.includes(route), true, `Missing route ${route}`);
console.log(JSON.stringify({ ok: true, checks: ['route scanner detected purpose, walkthrough, truth validation, article enrichment, article review, article remediation, replay, publish scheduling, auth, agency, backlink routes, and workspace bundle routes, proof matrix routes, walkthrough-run routes, and report routes, release-gate routes, and readiness / contract-truth routes plus strategy routes plus runtime contracts, provider validation, claim evidence, proof-site routes, and live-target probe routes plus cutover routes and rollback routes'] }, null, 2));
