/* V38 AE FLOW searchable academy, troubleshooting recipes, reports, and badges */
(function(){
  if(window.__AEFLOW_V38_ENABLEMENT__) return;
  window.__AEFLOW_V38_ENABLEMENT__ = true;

  const FULL_PROGRESS_KEY = 'skye_aeflow_tutorial_progress_v2';
  const MINI_PROGRESS_KEY = 'skye_aeflow_mini_progress_v1';
  const REPORTS_KEY = 'skye_aeflow_learning_reports_v38';
  const SEARCH_HISTORY_KEY = 'skye_aeflow_help_search_history_v38';

  const TOUR_ITEMS = [
    { id:'aeflow-start-here', title:'Start here • Core AE FLOW', keywords:'intake accounts deals settings tutorial center onboarding', description:'Guided first-use pass through intake, accounts, deals, and settings.' },
    { id:'aeflow-accounts-to-routex', title:'Accounts to Routex • Queue and seed flow', keywords:'accounts queue routex seed bridge queue visible', description:'Shows how accounts become Routex-visible work and seed exports.' },
    { id:'aeflow-proof-and-proposals', title:'Proof and proposals', keywords:'proof record proposal export deals', description:'Explains proof, proposals, and export-ready record surfaces.' },
    { id:'aeflow-bridge-sync-inboxes', title:'Bridge sync and inboxes', keywords:'sync inbox routex launch board ops brief handoff binder', description:'Focused pass for the Routex sync command row and inbox surfaces.' },
    { id:'aeflow-lineage-and-transfer', title:'Lineage and transfer', keywords:'legacy transfer capsules attestation lineage', description:'Shows lineage, compare, capsules, and attestation flows.' },
    { id:'aeflow-settings-and-tutorials', title:'Settings and tutorials', keywords:'settings backup reset tutorial academy', description:'Settings controls, recovery, and built-in learning surfaces.' }
  ];
  const MINI_ITEMS = [
    { id:'mini-routex-seed', title:'Micro guide • Queue visible accounts', keywords:'queue visible accounts seed routex bridge', description:'Shortest bridge path from accounts into Routex-ready queue and seeds.' },
    { id:'mini-proof-record', title:'Micro guide • Record proof and export', keywords:'proof record export proposal deals', description:'Quick proof pass from record view to export.' },
    { id:'mini-sync-command', title:'Micro guide • Sync command row', keywords:'launch board ops brief handoff binder receipt sync', description:'Fast pass across the Routex sync command row.' },
    { id:'mini-lineage-sync', title:'Micro guide • Legacy, transfer, attestation', keywords:'legacy transfer attestation capsule lineage', description:'Short lineage pass for legacy sync, capsules, and attestations.' },
    { id:'mini-settings-recovery', title:'Micro guide • Settings and recovery', keywords:'settings recovery presets reset tutorial', description:'Fast pass for presets, resets, and tutorial access.' }
  ];
  const ROLE_PACKS = [
    { id:'pack-ae-core', title:'AE core badge', summary:'Core AE FLOW, Routex seed bridge, proof records, and settings.', items:[['tour','aeflow-start-here'],['tour','aeflow-accounts-to-routex'],['mini','mini-proof-record'],['mini','mini-settings-recovery']] },
    { id:'pack-bridge-command', title:'Bridge command badge', summary:'Seed bridge, sync command row, launch board, handoff, binder, and receipt visibility.', items:[['tour','aeflow-bridge-sync-inboxes'],['mini','mini-routex-seed'],['mini','mini-sync-command']] },
    { id:'pack-lineage-trust', title:'Lineage and trust badge', summary:'Legacy sync, transfer compare, capsules, attestations, and settings recovery.', items:[['tour','aeflow-lineage-and-transfer'],['mini','mini-lineage-sync'],['mini','mini-settings-recovery']] },
    { id:'pack-proof-operator', title:'Proof operator badge', summary:'Deals, proof, exports, and operator-ready record visibility.', items:[['tour','aeflow-proof-and-proposals'],['mini','mini-proof-record'],['mini','mini-sync-command']] }
  ];
  const RECIPES = [
    { id:'ae-recipe-new', title:'Troubleshooting recipe • I am new to AE FLOW', keywords:'new start onboarding intake accounts deals', symptom:'The user needs the safest starting path through intake, accounts, deals, and settings.', steps:['Run the core AE FLOW tour first.','Use settings and tutorials so the learning surface is visible early.'], actions:[['tour','aeflow-start-here','Start core tour'],['tour','aeflow-settings-and-tutorials','Open settings/tutorials']] },
    { id:'ae-recipe-bridge', title:'Troubleshooting recipe • I need the Routex bridge story', keywords:'bridge queue routex seed sync', symptom:'The operator wants the shortest explanation of how AE FLOW feeds Routex.', steps:['Run accounts to Routex first.','Use the queue visible accounts micro guide for the shortest bridge move.'], actions:[['tour','aeflow-accounts-to-routex','Run accounts to Routex'],['mini','mini-routex-seed','Open queue visible guide']] },
    { id:'ae-recipe-proof', title:'Troubleshooting recipe • I do not understand record proof or proposals', keywords:'proof record proposal export deals', symptom:'The record and proof surfaces need a guided explanation instead of only raw buttons.', steps:['Run proof and proposals first.','Use the record proof micro guide for the shortest focused pass.'], actions:[['tour','aeflow-proof-and-proposals','Run proof and proposals'],['mini','mini-proof-record','Open proof record guide']] },
    { id:'ae-recipe-sync', title:'Troubleshooting recipe • The sync command row feels too dense', keywords:'sync command row launch board ops brief handoff binder receipt', symptom:'The user sees many sync controls but wants the shortest path to understand them.', steps:['Run bridge sync and inboxes.','Use the sync command micro guide for a compact pass.'], actions:[['tour','aeflow-bridge-sync-inboxes','Run bridge sync and inboxes'],['mini','mini-sync-command','Open sync command guide']] },
    { id:'ae-recipe-lineage', title:'Troubleshooting recipe • I need lineage, transfer, or attestation clarity', keywords:'legacy transfer attestation capsule lineage', symptom:'History and proof surfaces are visible but the user needs a guided sequence.', steps:['Run lineage and transfer first.','Use the lineage sync micro guide for the shortest pass.'], actions:[['tour','aeflow-lineage-and-transfer','Run lineage and transfer'],['mini','mini-lineage-sync','Open lineage sync guide']] },
    { id:'ae-recipe-settings', title:'Troubleshooting recipe • I need settings, presets, or tutorial recovery', keywords:'settings presets reset tutorial academy recovery', symptom:'The operator wants settings and recovery explained cleanly.', steps:['Run settings and tutorials.','Use the settings and recovery micro guide for the shortest path.'], actions:[['tour','aeflow-settings-and-tutorials','Run settings and tutorials'],['mini','mini-settings-recovery','Open settings recovery guide']] }
  ];

  const clean = (v)=> String(v == null ? '' : v).trim();
  const esc = (v)=> String(v == null ? '' : v).replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const toast = window.toast || function(){};

  function readJSON(key, fallback){ try{ const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) : fallback; }catch(_){ return fallback; } }
  function writeJSON(key, value){ try{ localStorage.setItem(key, JSON.stringify(value)); }catch(_){} return value; }
  function readFull(){ return readJSON(FULL_PROGRESS_KEY, {}); }
  function readMini(){ return readJSON(MINI_PROGRESS_KEY, {}); }
  function readReports(){ return readJSON(REPORTS_KEY, []); }
  function saveReports(list){ return writeJSON(REPORTS_KEY, list || []); }
  function readSearchHistory(){ return readJSON(SEARCH_HISTORY_KEY, []); }
  function saveSearchHistory(list){ return writeJSON(SEARCH_HISTORY_KEY, list || []); }
  function dayISO(){ return new Date().toISOString().slice(0,10); }
  function uid(){ return 'aeflow-v38-' + Math.random().toString(36).slice(2,10) + '-' + Date.now().toString(36); }
  function downloadText(text, filename, mime){ try{ if(typeof window.downloadText === 'function') return window.downloadText(text, filename, mime || 'text/plain'); }catch(_){} const blob = new Blob([String(text == null ? '' : text)], { type: mime || 'text/plain' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = filename || ('download-' + Date.now() + '.txt'); document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=> URL.revokeObjectURL(url), 500); }
  function readCombined(){ return { full: readFull(), mini: readMini() }; }
  function itemDone(kind, id, maps){ maps = maps || readCombined(); const row = kind === 'tour' ? maps.full[id] : maps.mini[id]; return !!(row && row.completedAt); }
  function badgeRows(){ const maps = readCombined(); return ROLE_PACKS.map(pack => { const total = pack.items.length; const done = pack.items.filter(([kind,id]) => itemDone(kind,id,maps)).length; const pct = Math.round((done / Math.max(1,total)) * 100); return { id:pack.id, title:pack.title, summary:pack.summary, total, done, pct, complete: done === total, state: done === total ? 'Unlocked' : (done ? 'In progress' : 'Locked') }; }); }
  function latestLearningRows(){ const rows = []; const maps = readCombined(); Object.entries(maps.full).forEach(([id,row])=> rows.push({ kind:'Tour', id, updatedAt:String((row||{}).updatedAt||''), done:!!(row&&row.completedAt) })); Object.entries(maps.mini).forEach(([id,row])=> rows.push({ kind:'Micro', id, updatedAt:String((row||{}).updatedAt||''), done:!!(row&&row.completedAt) })); return rows.filter(r => r.updatedAt).sort((a,b)=> b.updatedAt.localeCompare(a.updatedAt)).slice(0,10); }
  function buildReport(){ const maps = readCombined(); const toursDone = TOUR_ITEMS.filter(item => itemDone('tour', item.id, maps)).length; const minisDone = MINI_ITEMS.filter(item => itemDone('mini', item.id, maps)).length; const badges = badgeRows(); const recent = latestLearningRows(); const nextTour = TOUR_ITEMS.find(item => !itemDone('tour', item.id, maps)); const nextMini = MINI_ITEMS.find(item => !itemDone('mini', item.id, maps)); const overallTotal = TOUR_ITEMS.length + MINI_ITEMS.length; const overallDone = toursDone + minisDone; const pct = Math.round((overallDone / Math.max(1, overallTotal)) * 100); return { id:uid(), createdAt:new Date().toISOString(), source:'aeflow-academy-v38', overall:{ done:overallDone, total:overallTotal, pct }, tours:{ done:toursDone, total:TOUR_ITEMS.length }, miniGuides:{ done:minisDone, total:MINI_ITEMS.length }, badges, nextSuggested:{ nextTour: nextTour ? nextTour.title : 'All tours completed', nextMiniGuide: nextMini ? nextMini.title : 'All micro guides completed' }, recentActivity: recent }; }
  function saveReport(){ const row = buildReport(); const list = readReports().filter(item => clean(item && item.id) !== clean(row.id)); list.unshift(row); saveReports(list.slice(0, 30)); return row; }
  function reportHtml(row){ row = row || buildReport(); const badges = (row.badges || []).map(item => `<tr><td>${esc(item.title)}</td><td>${esc(String(item.done))}/${esc(String(item.total))}</td><td>${esc(String(item.pct))}%</td><td>${esc(item.state)}</td></tr>`).join(''); const recent = (row.recentActivity || []).map(item => `<tr><td>${esc(item.kind)}</td><td>${esc(item.id)}</td><td>${item.done ? 'Completed' : 'In progress'}</td><td>${esc(item.updatedAt)}</td></tr>`).join(''); return `<!doctype html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>AE FLOW learning report</title><style>body{font-family:ui-sans-serif,system-ui;background:#05000a;color:#fff;padding:24px}.wrap{max-width:1040px;margin:0 auto}.card{border:1px solid rgba(255,255,255,.12);border-radius:18px;background:rgba(255,255,255,.04);padding:18px;margin:0 0 18px}.badge{display:inline-block;padding:4px 8px;border:1px solid rgba(255,255,255,.16);border-radius:999px;margin:0 6px 6px 0}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-bottom:1px solid rgba(255,255,255,.1);text-align:left}</style></head><body><div class="wrap"><div class="card"><h1 style="margin:0 0 8px;">AE FLOW • Learning completion report</h1><div><span class="badge">Overall ${esc(String(row.overall.pct))}%</span><span class="badge">Tours ${esc(String(row.tours.done))}/${esc(String(row.tours.total))}</span><span class="badge">Micro guides ${esc(String(row.miniGuides.done))}/${esc(String(row.miniGuides.total))}</span><span class="badge">Generated ${esc(row.createdAt)}</span></div><p style="margin:12px 0 0;">Next tour: ${esc(row.nextSuggested.nextTour)} • Next micro guide: ${esc(row.nextSuggested.nextMiniGuide)}</p></div><div class="card"><h2 style="margin:0 0 8px;">Role-pack badges</h2><table><thead><tr><th>Badge</th><th>Progress</th><th>Score</th><th>Status</th></tr></thead><tbody>${badges || '<tr><td colspan="4">No badge rows.</td></tr>'}</tbody></table></div><div class="card"><h2 style="margin:0 0 8px;">Recent learning activity</h2><table><thead><tr><th>Kind</th><th>ID</th><th>Status</th><th>Updated</th></tr></thead><tbody>${recent || '<tr><td colspan="4">No recent activity recorded yet.</td></tr>'}</tbody></table></div></div></body></html>`; }
  function exportReportJson(){ const row = saveReport(); downloadText(JSON.stringify(row, null, 2), 'ae_flow_learning_report_' + dayISO() + '.json', 'application/json'); toast('AE FLOW learning report JSON exported.', 'good'); }
  function exportReportHtml(){ const row = saveReport(); downloadText(reportHtml(row), 'ae_flow_learning_report_' + dayISO() + '.html', 'text/html'); toast('AE FLOW learning report HTML exported.', 'good'); }
  function buildSearchItems(){ const items = []; TOUR_ITEMS.forEach(item => items.push({ kind:'tour', id:item.id, title:item.title, description:item.description, keywords:item.keywords })); MINI_ITEMS.forEach(item => items.push({ kind:'mini', id:item.id, title:item.title, description:item.description, keywords:item.keywords })); RECIPES.forEach(item => items.push({ kind:'recipe', id:item.id, title:item.title, description:item.symptom, keywords:item.keywords })); items.push({ kind:'action', id:'badges', title:'Role-pack badges board', description:'See which AE FLOW job packs are complete and what still unlocks them.', keywords:'badge board role packs status' }); items.push({ kind:'action', id:'reports', title:'Learning completion report', description:'Export HTML or JSON completion reports for the learning stack.', keywords:'learning report export html json analytics' }); return items; }
  function scoreItem(item, q){ const hay = (item.title + ' ' + item.description + ' ' + item.keywords).toLowerCase(); const terms = clean(q).toLowerCase().split(/\s+/).filter(Boolean); if(!terms.length) return 1; let score = 0; for(const term of terms){ if(!hay.includes(term)) return 0; if(item.title.toLowerCase().includes(term)) score += 4; else if(item.keywords.toLowerCase().includes(term)) score += 2; else score += 1; } return score; }
  function filteredSearch(q){ return buildSearchItems().map(item => ({ item, score: scoreItem(item, q) })).filter(row => row.score > 0).sort((a,b)=> b.score - a.score || a.item.title.localeCompare(b.item.title)).map(row => row.item).slice(0,24); }
  function saveSearchTerm(q){ q = clean(q); if(!q) return; const list = readSearchHistory().filter(item => clean(item) !== q); list.unshift(q); saveSearchHistory(list.slice(0, 12)); }
  function runAction(kind, id){ try{ document.getElementById('modalClose')?.click(); }catch(_){} if(kind === 'tour' && typeof window.startAEFlowInteractiveTour === 'function') return window.startAEFlowInteractiveTour(id); if(kind === 'mini' && typeof window.startAEFlowMiniGuide === 'function') return window.startAEFlowMiniGuide(id); if(kind === 'recipe') return openRecipes(id); if(kind === 'action' && id === 'badges') return openBadgeBoard(); if(kind === 'action' && id === 'reports') return openReportBoard(); }
  function openDialog(title, body, footer){ if(typeof window.openModal === 'function') return window.openModal(title, body, footer || `<button class="btn" onclick="document.getElementById('modalClose').click()">Close</button>`); const wrap = document.createElement('div'); wrap.id = 'modalWrap'; wrap.innerHTML = `<div style="position:fixed;inset:0;background:rgba(0,0,0,.66);z-index:99999;display:flex;align-items:center;justify-content:center;padding:18px;"><div style="max-width:940px;width:100%;max-height:86vh;overflow:auto;background:#13071f;color:#fff;border:1px solid rgba(255,255,255,.12);border-radius:20px;padding:18px;"><div class="row" style="justify-content:space-between;gap:12px;"><h2 style="margin:0;">${esc(title)}</h2><button class="btn" id="modalClose" type="button">Close</button></div><div id="modalBody">${body}</div><div style="margin-top:12px;">${footer || ''}</div></div></div>`; document.body.appendChild(wrap); document.getElementById('modalClose')?.addEventListener('click', ()=> wrap.remove()); }
  function ensureStyle(){ if(document.getElementById('aeV38EnablementStyles')) return; const style = document.createElement('style'); style.id = 'aeV38EnablementStyles'; style.textContent = `.ae-v38-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:10px}.ae-v38-card{border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.04);border-radius:16px;padding:12px}.ae-v38-card h4{margin:0 0 6px;font-size:14px}.ae-v38-card p{margin:0 0 8px;font-size:12px;line-height:1.45;color:rgba(255,255,255,.76)}.ae-v38-mini{font-size:11px;color:rgba(255,255,255,.58)}.ae-v38-table{width:100%;border-collapse:collapse}.ae-v38-table th,.ae-v38-table td{padding:8px;border-bottom:1px solid rgba(255,255,255,.08);text-align:left;vertical-align:top;font-size:12px}`; document.head.appendChild(style); }
  function bindSearchModal(){ const input = document.getElementById('aeV38SearchInput'); const results = document.getElementById('aeV38SearchResults'); const chips = document.querySelectorAll('[data-ae-v38-chip]'); function render(q){ const items = filteredSearch(q); results.innerHTML = items.length ? items.map(item => `<div class="ae-v38-card"><h4>${esc(item.title)}</h4><p>${esc(item.description)}</p><div class="ae-v38-mini">${esc(item.keywords)}</div><div class="sep"></div><button class="btn small" data-ae-v38-run="${esc(item.kind)}::${esc(item.id)}">Open</button></div>`).join('') : '<div class="hint">No matching academy item yet.</div>'; results.querySelectorAll('[data-ae-v38-run]').forEach(btn => btn.onclick = ()=>{ const [kind,id] = String(btn.getAttribute('data-ae-v38-run')||'').split('::'); if(clean(input.value)) saveSearchTerm(input.value); runAction(kind,id); }); } input?.addEventListener('input', ()=> render(input.value)); chips.forEach(chip => chip.onclick = ()=>{ if(input) input.value = chip.getAttribute('data-ae-v38-chip') || ''; render(input.value || ''); }); render(input && input.value || ''); }
  function openSearch(prefill){ const history = readSearchHistory(); const seedChips = (history.length ? history : ['bridge','proof','settings','lineage','sync']).map(item => `<button class="btn small" type="button" data-ae-v38-chip="${esc(item)}">${esc(item)}</button>`).join(''); const body = `<div class="hint">Search every AE FLOW tour, micro guide, recipe, report, and badge board from one place so the bridge-heavy product stays easy to interrogate.</div><div class="sep"></div><input id="aeV38SearchInput" class="input" placeholder="Search help, guides, or recipes" value="${esc(prefill || '')}"/><div class="sep"></div><div class="row" style="flex-wrap:wrap; gap:8px;">${seedChips}</div><div class="sep"></div><div class="ae-v38-grid" id="aeV38SearchResults"></div>`; openDialog('AE FLOW help search', body, `<button class="btn" onclick="document.getElementById('modalClose').click()">Close</button>`); setTimeout(bindSearchModal, 0); }
  function bindRecipesModal(){ document.querySelectorAll('[data-ae-v38-recipe-action]').forEach(btn => btn.onclick = ()=>{ const [kind,id] = String(btn.getAttribute('data-ae-v38-recipe-action') || '').split('::'); runAction(kind,id); }); document.querySelectorAll('[data-ae-v38-search-recipe]').forEach(btn => btn.onclick = ()=> openSearch(btn.getAttribute('data-ae-v38-search-recipe'))); }
  function openRecipes(focusId){ const rows = (focusId ? RECIPES.filter(item => item.id === focusId) : RECIPES); const body = `<div class="hint">These troubleshooting recipes turn common AE FLOW confusion into guided recovery moves. Each recipe can launch the exact tour or micro guide that resolves the issue.</div><div class="sep"></div><div class="ae-v38-grid">${rows.map(item => `<div class="ae-v38-card"><h4>${esc(item.title)}</h4><p>${esc(item.symptom)}</p><div class="ae-v38-mini">${esc(item.keywords)}</div><div class="sep"></div><ul>${item.steps.map(step => `<li>${esc(step)}</li>`).join('')}</ul><div class="sep"></div><div class="row" style="flex-wrap:wrap; gap:8px;">${item.actions.map(row => `<button class="btn small" type="button" data-ae-v38-recipe-action="${esc(row[0])}::${esc(row[1])}">${esc(row[2])}</button>`).join('')}<button class="btn small" type="button" data-ae-v38-search-recipe="${esc(item.keywords.split(' ')[0] || item.title)}">Search related help</button></div></div>`).join('')}</div>`; openDialog('AE FLOW troubleshooting recipes', body, `<button class="btn" onclick="document.getElementById('modalClose').click()">Close</button>`); setTimeout(bindRecipesModal, 0); }
  function openBadgeBoard(){ const rows = badgeRows(); const body = `<div class="hint">Role-pack badges let AE FLOW prove which job packs are already learned and which still need guided coverage.</div><div class="sep"></div><div class="ae-v38-grid">${rows.map(item => `<div class="ae-v38-card"><h4>${esc(item.title)}</h4><p>${esc(item.summary)}</p><div class="row" style="flex-wrap:wrap; gap:8px;"><div class="pill">${esc(item.state)}</div><div class="pill">${esc(String(item.done))}/${esc(String(item.total))}</div><div class="pill">${esc(String(item.pct))}%</div></div></div>`).join('')}</div><div class="sep"></div><div class="row" style="flex-wrap:wrap; gap:8px;"><button class="btn" id="aeV38ExportBadgeHtml">Export learning HTML</button><button class="btn" id="aeV38ExportBadgeJson">Export learning JSON</button></div>`; openDialog('AE FLOW badge board', body, `<button class="btn" onclick="document.getElementById('modalClose').click()">Close</button>`); setTimeout(()=>{ document.getElementById('aeV38ExportBadgeHtml')?.addEventListener('click', exportReportHtml); document.getElementById('aeV38ExportBadgeJson')?.addEventListener('click', exportReportJson); }, 0); }
  function openReportBoard(){ const reports = readReports(); const latest = reports[0] || buildReport(); const rows = reports.length ? reports.map(item => `<tr><td>${esc(item.createdAt)}</td><td>${esc(String((item.overall||{}).pct || 0))}%</td><td>${esc(String(((item.badges||[]).filter(r => r.complete).length)))} complete badge(s)</td></tr>`).join('') : '<tr><td colspan="3">No saved report rows yet. Export one now.</td></tr>'; const body = `<div class="hint">Learning completion reports make the AE FLOW education layer visible, exportable, and auditable from inside the product.</div><div class="sep"></div><div class="row" style="flex-wrap:wrap; gap:8px;"><div class="pill">Overall ${esc(String((latest.overall||{}).pct || 0))}%</div><div class="pill">Tours ${esc(String(((latest.tours||{}).done || 0)))} / ${esc(String(((latest.tours||{}).total || 0)))}</div><div class="pill">Micro guides ${esc(String(((latest.miniGuides||{}).done || 0)))} / ${esc(String(((latest.miniGuides||{}).total || 0)))}</div></div><div class="sep"></div><table class="ae-v38-table"><thead><tr><th>Generated</th><th>Overall</th><th>Badge state</th></tr></thead><tbody>${rows}</tbody></table><div class="sep"></div><div class="row" style="flex-wrap:wrap; gap:8px;"><button class="btn" id="aeV38ExportLearningHtml">Export report HTML</button><button class="btn" id="aeV38ExportLearningJson">Export report JSON</button></div>`; openDialog('AE FLOW learning reports', body, `<button class="btn" onclick="document.getElementById('modalClose').click()">Close</button>`); setTimeout(()=>{ document.getElementById('aeV38ExportLearningHtml')?.addEventListener('click', exportReportHtml); document.getElementById('aeV38ExportLearningJson')?.addEventListener('click', exportReportJson); }, 0); }
  function bindCardButtons(){ document.getElementById('aeV38CardSearch')?.addEventListener('click', ()=> openSearch('')); document.getElementById('aeV38CardRecipes')?.addEventListener('click', ()=> openRecipes('')); document.getElementById('aeV38CardReports')?.addEventListener('click', openReportBoard); }
  function dashboardCardHtml(){ const badges = badgeRows(); const completeBadges = badges.filter(item => item.complete).length; return `<h2>Searchable academy and troubleshooting</h2><div class="hint">Search every tour and micro guide, open fix recipes, export learning reports, and track role-pack badges from one visible AE FLOW command lane.</div><div class="sep"></div><div class="row" style="flex-wrap:wrap; gap:8px;"><div class="pill">Badges ${esc(String(completeBadges))}/${esc(String(badges.length))}</div><div class="pill">Reports ${esc(String(readReports().length))}</div><button class="btn" id="aeV38CardSearch">Search help</button><button class="btn" id="aeV38CardRecipes">Fix recipes</button><button class="btn" id="aeV38CardReports">Learning reports</button></div>`; }
  function currentTab(){ try{ return clean((window.state && state.activeTab) || 'intake'); }catch(_){ return 'intake'; } }
  function inject(){ ensureStyle(); const host = document.querySelector('.topbar .row:last-of-type') || document.querySelector('.topbar .row') || document.querySelector('.toolbar') || document.querySelector('.row'); if(host && !document.getElementById('aeV38SearchBtn')){ const searchBtn = document.createElement('button'); searchBtn.className='btn'; searchBtn.id='aeV38SearchBtn'; searchBtn.textContent='Help Search'; searchBtn.onclick = ()=> openSearch(''); const recipeBtn = document.createElement('button'); recipeBtn.className='btn'; recipeBtn.id='aeV38RecipeBtn'; recipeBtn.textContent='Fix Recipes'; recipeBtn.onclick = ()=> openRecipes(''); const reportBtn = document.createElement('button'); reportBtn.className='btn'; reportBtn.id='aeV38ReportBtn'; reportBtn.textContent='Learning Reports'; reportBtn.onclick = openReportBoard; const badgeBtn = document.createElement('button'); badgeBtn.className='btn'; badgeBtn.id='aeV38BadgeBtn'; badgeBtn.textContent='Badge Board'; badgeBtn.onclick = openBadgeBoard; host.appendChild(searchBtn); host.appendChild(recipeBtn); host.appendChild(reportBtn); host.appendChild(badgeBtn); }
    const main = document.querySelector('#app') || document.body;
    if(currentTab() === 'intake' && !document.getElementById('aeV38DashboardHelpCard')){ const card = document.createElement('div'); card.className='card'; card.id='aeV38DashboardHelpCard'; card.innerHTML = dashboardCardHtml(); main.prepend(card); bindCardButtons(); }
    if(currentTab() === 'settings' && !document.getElementById('aeV38SettingsHelpCard')){ const card = document.createElement('div'); card.className='card'; card.id='aeV38SettingsHelpCard'; card.innerHTML = `<h2>Academy command lane</h2><div class="hint">This settings card keeps help search, troubleshooting recipes, reports, and role-pack badges visible inside AE FLOW.</div><div class="sep"></div><div class="row" style="flex-wrap:wrap; gap:8px;"><button class="btn" id="aeV38SettingsSearch">Search help</button><button class="btn" id="aeV38SettingsRecipes">Open recipes</button><button class="btn" id="aeV38SettingsReports">Export reports</button><button class="btn" id="aeV38SettingsBadges">View badges</button></div>`; main.prepend(card); document.getElementById('aeV38SettingsSearch')?.addEventListener('click', ()=> openSearch('')); document.getElementById('aeV38SettingsRecipes')?.addEventListener('click', ()=> openRecipes('')); document.getElementById('aeV38SettingsReports')?.addEventListener('click', openReportBoard); document.getElementById('aeV38SettingsBadges')?.addEventListener('click', openBadgeBoard); }
  }
  const observer = new MutationObserver(()=> inject()); observer.observe(document.documentElement || document.body, { childList:true, subtree:true }); const prevRender = window.renderAll; if(typeof prevRender === 'function' && !window.__AEFLOW_V38_RENDER_WRAPPED__){ window.__AEFLOW_V38_RENDER_WRAPPED__ = true; window.renderAll = function(){ const out = prevRender.apply(this, arguments); setTimeout(inject, 0); return out; }; }
  window.openAEFlowAcademySearch = openSearch; window.openAEFlowTroubleshootingRecipes = openRecipes; window.openAEFlowLearningReports = openReportBoard; window.openAEFlowBadgeBoard = openBadgeBoard; window.exportAEFlowLearningReportHtml = exportReportHtml; window.exportAEFlowLearningReportJson = exportReportJson; if(document.readyState === 'loading') document.addEventListener('DOMContentLoaded', ()=> setTimeout(inject, 120)); else setTimeout(inject, 120);
})();
