/* V54 AE FLOW resolution + saturation visibility */
(function(){
  if(window.__AEFLOW_WHITEGLOVE_V54__) return;
  window.__AEFLOW_WHITEGLOVE_V54__ = true;
  const KEYS = {
    resolutionRows:'skye_whiteglove_collision_resolution_plans_v54', resolutionOutbox:'skye_whiteglove_collision_resolution_outbox_v54', resolutionInbox:'ae_whiteglove_collision_resolution_inbox_v54',
    saturationRows:'skye_whiteglove_surface_saturation_v54', saturationOutbox:'skye_whiteglove_surface_saturation_outbox_v54', saturationInbox:'ae_whiteglove_surface_saturation_inbox_v54'
  };
  const clean = (v)=> String(v == null ? '' : v).trim();
  const esc = (v)=> String(v == null ? '' : v).replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const toast = window.toast || function(msg){ try{ console.log(msg); }catch(_){} };
  const downloadText = window.downloadText || function(content, filename, type){ const blob = new Blob([content], { type: type || 'text/plain' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = filename || 'download.txt'; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=> URL.revokeObjectURL(url), 1200); };
  const readJSON = (k,f)=> { try{ const raw = localStorage.getItem(k); return raw ? JSON.parse(raw) : f; }catch(_){ return f; } };
  const writeJSON = (k,v)=> { try{ localStorage.setItem(k, JSON.stringify(v)); }catch(_){} return v; };
  const latest = (key)=> readJSON(key, [])[0] || null;
  function sync(refKey, rowsKey, inboxKey, idField){ const refs = readJSON(refKey, []); const rows = readJSON(rowsKey, []); const inbox = readJSON(inboxKey, []); const seen = new Set(inbox.map(r => clean(r && r.id)).filter(Boolean)); refs.forEach(ref => { const id = clean(ref && ref[idField]); const row = rows.find(item => clean(item && item.id) === id); if(row && !seen.has(id)){ inbox.unshift(row); seen.add(id); } }); writeJSON(inboxKey, inbox.slice(0, 240)); return inbox; }
  const htmlWrap = (title, rows)=> '<!doctype html><html><head><meta charset="utf-8"><title>'+esc(title)+'</title><style>body{font-family:Arial,sans-serif;padding:24px;color:#111}.wrap{max-width:1080px;margin:0 auto}.card{border:1px solid #ddd;border-radius:18px;padding:16px;white-space:pre-wrap}</style></head><body><div class="wrap"><div class="card"><h1>'+esc(title)+'</h1><pre>'+esc(JSON.stringify(rows || [], null, 2))+'</pre></div></div></body></html>';
  function ensureUI(){
    if(document.getElementById('ae-wg-v54-launcher')) return;
    const launcher = document.createElement('button'); launcher.id = 'ae-wg-v54-launcher'; launcher.textContent = 'WG Resolve View+'; launcher.style.cssText = 'position:fixed;left:18px;bottom:120px;z-index:100009;border:1px solid rgba(255,255,255,.18);background:#19424f;color:#fff;padding:10px 14px;border-radius:999px;font:700 12px system-ui;box-shadow:0 12px 28px rgba(0,0,0,.35);cursor:pointer;';
    const modal = document.createElement('div'); modal.id = 'ae-wg-v54-modal'; modal.style.cssText = 'display:none;position:fixed;inset:0;z-index:100010;background:rgba(0,0,0,.72);padding:24px;overflow:auto;';
    modal.innerHTML = '<div style="max-width:1180px;margin:0 auto;background:#12081f;color:#fff;border:1px solid rgba(255,255,255,.14);border-radius:24px;padding:18px 18px 26px"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:14px"><div><div style="font:700 20px system-ui">White-glove resolution visibility</div><div style="font:12px system-ui;opacity:.72">AE FLOW view of collision-resolution plans and final surface saturation rows.</div></div><button id="ae-wg-v54-close" style="border:1px solid rgba(255,255,255,.16);background:rgba(255,255,255,.06);color:#fff;padding:8px 12px;border-radius:12px;cursor:pointer">Close</button></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:16px"><section style="border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:14px"><div style="display:flex;justify-content:space-between;align-items:center"><h3 style="margin:0">Resolution inbox</h3><div><button id="ae-wg-v54-sync-resolution" style="margin-right:8px">Sync</button><button id="ae-wg-v54-export-resolution-json">Export JSON</button></div></div><pre id="ae-wg-v54-resolution" style="white-space:pre-wrap;background:rgba(255,255,255,.04);padding:12px;border-radius:14px;max-height:280px;overflow:auto"></pre></section><section style="border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:14px"><div style="display:flex;justify-content:space-between;align-items:center"><h3 style="margin:0">Saturation inbox</h3><div><button id="ae-wg-v54-sync-saturation" style="margin-right:8px">Sync</button><button id="ae-wg-v54-export-saturation-html" style="margin-right:8px">Export HTML</button><button id="ae-wg-v54-export-saturation-json">Export JSON</button></div></div><pre id="ae-wg-v54-saturation" style="white-space:pre-wrap;background:rgba(255,255,255,.04);padding:12px;border-radius:14px;max-height:280px;overflow:auto"></pre></section><section style="border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:14px"><h3 style="margin:0 0 10px">Why this matters</h3><div style="font:13px system-ui;line-height:1.6;opacity:.86">AE FLOW can now see when Routex has prepared a safe collision-resolution plan and whether the newest operator surfaces are saturated across value, proof, conflict, backend, and guide coverage.</div><div style="margin-top:12px;display:flex;gap:8px;flex-wrap:wrap"><button id="ae-wg-v54-run-guide">Run guide</button></div></section><section style="border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:14px"><h3 style="margin:0 0 10px">Latest summary</h3><pre id="ae-wg-v54-summary" style="white-space:pre-wrap;background:rgba(255,255,255,.04);padding:12px;border-radius:14px;max-height:220px;overflow:auto"></pre></section></div></div>';
    document.body.appendChild(launcher); document.body.appendChild(modal);
    const refresh = ()=> { const latestResolution = latest(KEYS.resolutionInbox); const latestSaturation = latest(KEYS.saturationInbox); modal.querySelector('#ae-wg-v54-resolution').textContent = JSON.stringify(latestResolution, null, 2); modal.querySelector('#ae-wg-v54-saturation').textContent = JSON.stringify(latestSaturation, null, 2); modal.querySelector('#ae-wg-v54-summary').textContent = JSON.stringify({ latestResolutionId: latestResolution && latestResolution.id, latestSaturationId: latestSaturation && latestSaturation.id, blockers: latestSaturation && latestSaturation.blockers || [] }, null, 2); };
    launcher.onclick = ()=> { modal.style.display='block'; refresh(); };
    modal.querySelector('#ae-wg-v54-close').onclick = ()=> { modal.style.display='none'; };
    modal.querySelector('#ae-wg-v54-sync-resolution').onclick = ()=> { sync(KEYS.resolutionOutbox, KEYS.resolutionRows, KEYS.resolutionInbox, 'resolutionPlanId'); refresh(); toast('White-glove resolution inbox synced.','good'); };
    modal.querySelector('#ae-wg-v54-sync-saturation').onclick = ()=> { sync(KEYS.saturationOutbox, KEYS.saturationRows, KEYS.saturationInbox, 'saturationId'); refresh(); toast('White-glove saturation inbox synced.','good'); };
    modal.querySelector('#ae-wg-v54-export-resolution-json').onclick = ()=> downloadText(JSON.stringify(readJSON(KEYS.resolutionInbox, []), null, 2), 'ae_whiteglove_resolution_inbox_v54.json', 'application/json');
    modal.querySelector('#ae-wg-v54-export-saturation-html').onclick = ()=> downloadText(htmlWrap('AE white-glove surface saturation inbox', readJSON(KEYS.saturationInbox, [])), 'ae_whiteglove_saturation_inbox_v54.html', 'text/html');
    modal.querySelector('#ae-wg-v54-export-saturation-json').onclick = ()=> downloadText(JSON.stringify(readJSON(KEYS.saturationInbox, []), null, 2), 'ae_whiteglove_saturation_inbox_v54.json', 'application/json');
    modal.querySelector('#ae-wg-v54-run-guide').onclick = ()=> { if(typeof window.startAEWhiteGloveV54Tour === 'function') window.startAEWhiteGloveV54Tour(); else toast('V54 guide unavailable.','warn'); };
  }
  window.openAEWhiteGloveResolutionVisibilityV54 = function(){ ensureUI(); document.getElementById('ae-wg-v54-launcher')?.click(); };
  if(document.readyState === 'loading') document.addEventListener('DOMContentLoaded', ensureUI); else ensureUI();
})();
