/* V52 AE FLOW walkthroughs for valuation / chain audit / superdeck visibility */
(function(){
  if(window.__AEFLOW_WHITEGLOVE_TOURS_V52__) return;
  window.__AEFLOW_WHITEGLOVE_TOURS_V52__ = true;
  const wait = (ms)=> new Promise(r => setTimeout(r, ms));
  let overlay = null, active = null, target = null;
  function clearTarget(){ if(target){ target.classList.remove('tour-active-target'); target = null; } }
  function ensure(){ if(overlay) return overlay; overlay = document.createElement('div'); overlay.style.cssText='display:none;position:fixed;inset:0;z-index:100110;pointer-events:none;'; const style=document.createElement('style'); style.textContent='.tour-active-target{outline:3px solid #9f6bff!important;box-shadow:0 0 0 6px rgba(159,107,255,.18)!important;border-radius:14px!important}.ae52dock{position:fixed;right:22px;bottom:22px;max-width:420px;background:#12081f;color:#fff;border:1px solid rgba(255,255,255,.14);border-radius:22px;padding:16px;box-shadow:0 22px 50px rgba(0,0,0,.4);pointer-events:auto}.ae52body{font:13px/1.55 system-ui;color:rgba(255,255,255,.82)}'; document.head.appendChild(style); overlay.innerHTML='<div class="ae52dock"><div id="ae52meta" class="pill">Step 1 / 1</div><h3 id="ae52title" style="font:800 19px system-ui;margin:6px 0">White-glove guide</h3><div id="ae52body" class="ae52body"></div><div style="height:7px;border-radius:999px;background:rgba(255,255,255,.1);overflow:hidden;margin:14px 0"><i id="ae52bar" style="display:block;height:100%;width:0;background:linear-gradient(90deg,#f5c542,#9f6bff)"></i></div><div class="row" style="gap:8px;flex-wrap:wrap"><button class="btn small" id="ae52back">Back</button><button class="btn small" id="ae52next">Next</button><div class="spacer"></div><button class="btn small danger" id="ae52close">Close</button></div></div>'; document.body.appendChild(overlay); overlay.querySelector('#ae52back').onclick=()=>move(-1); overlay.querySelector('#ae52next').onclick=()=>move(1); overlay.querySelector('#ae52close').onclick=close; return overlay; }
  function steps(){ return [
    { before: async()=>{ if(typeof window.openAEWhiteGloveValueCenterV52 === 'function') window.openAEWhiteGloveValueCenterV52(); await wait(220); }, selector:'#ae-wg-v52-val', title:'Valuation visibility', body:'AE FLOW can now see the client-facing 2026 valuation lane, not just the operational data.' },
    { before: async()=>{ if(typeof window.openAEWhiteGloveValueCenterV52 === 'function') window.openAEWhiteGloveValueCenterV52(); await wait(220); }, selector:'#ae-wg-v52-chain', title:'Route-chain proof visibility', body:'This inbox brings Routex chain audits into the continuity side so user and operator support stay aligned.' },
    { before: async()=>{ if(typeof window.openAEWhiteGloveValueCenterV52 === 'function') window.openAEWhiteGloveValueCenterV52(); await wait(220); }, selector:'#ae-wg-v52-super', title:'Superdeck visibility', body:'The superdeck gives AE FLOW one concise command surface for value, readiness, and premium-service risk.' }
  ]; }
  async function apply(){ const list = steps(); const step = list[active.i]; if(!step) return; ensure(); if(typeof step.before==='function') await step.before(); clearTarget(); target = document.querySelector(step.selector); if(target){ target.classList.add('tour-active-target'); target.scrollIntoView({behavior:'smooth', block:'center'}); } overlay.style.display='block'; overlay.querySelector('#ae52meta').textContent='Step '+(active.i+1)+' / '+list.length; overlay.querySelector('#ae52title').textContent=step.title; overlay.querySelector('#ae52body').textContent=step.body; overlay.querySelector('#ae52bar').style.width=(((active.i+1)/list.length)*100).toFixed(1)+'%'; overlay.querySelector('#ae52next').textContent = active.i === list.length-1 ? 'Finish' : 'Next'; }
  async function move(delta){ const list = steps(); const next = active.i + delta; if(next < 0) return; if(next >= list.length){ close(); return; } active.i = next; await apply(); }
  function close(){ clearTarget(); if(overlay) overlay.style.display='none'; active = null; }
  window.startAEWhiteGloveV52Tour = function(){ active = { i:0 }; apply(); };
})();
