/* V51 AE FLOW walkthrough for operator deck bridge */
(function(){
  if(window.__AEFLOW_WHITEGLOVE_TOURS_V51__) return;
  window.__AEFLOW_WHITEGLOVE_TOURS_V51__ = true;
  const wait = (ms)=> new Promise(resolve => setTimeout(resolve, ms));
  let overlay = null, activeTarget = null, stepIndex = 0;
  const steps = [
    { selector:'#ae-wg-v51-launcher', title:'Open the white-glove bridge', body:'This bridge brings the Routex operator deck, duplication runs, and merge-policy runs into AE FLOW.' },
    { before: async()=>{ if(typeof window.openAEWhiteGloveBridgeV51 === 'function') window.openAEWhiteGloveBridgeV51(); await wait(180); }, selector:'#ae-wg-v51-sync-deck', title:'Sync the operator deck inbox', body:'AE FLOW can now pull the unified Routex operator deck into its own continuity workspace.' },
    { before: async()=>{ if(typeof window.openAEWhiteGloveBridgeV51 === 'function') window.openAEWhiteGloveBridgeV51(); await wait(180); }, selector:'#ae-wg-v51-sync-dup', title:'Sync duplication runs', body:'Duplication visibility keeps repeat, split, and rebuilt service chains visible to the operator side of AE FLOW.' },
    { before: async()=>{ if(typeof window.openAEWhiteGloveBridgeV51 === 'function') window.openAEWhiteGloveBridgeV51(); await wait(180); }, selector:'#ae-wg-v51-sync-merge', title:'Sync merge-policy runs', body:'Merge-policy inbox gives AE FLOW visibility into restore and portability hardening work from Routex.' }
  ];
  function clearTarget(){ if(activeTarget){ activeTarget.classList.remove('ae-wg51-target'); activeTarget = null; } }
  function ensureStyle(){ if(document.getElementById('aeWg51TourStyle')) return; const style = document.createElement('style'); style.id='aeWg51TourStyle'; style.textContent='.ae-wg51-target{position:relative !important; z-index:10012 !important; box-shadow:0 0 0 3px rgba(34,197,94,.95),0 0 0 9999px rgba(3,1,8,.56) !important; border-radius:16px !important;}'; document.head.appendChild(style); }
  function ensureOverlay(){ ensureStyle(); if(overlay) return overlay; overlay = document.createElement('div'); overlay.style.cssText='position:fixed;inset:0;z-index:10011;pointer-events:none;display:none'; overlay.innerHTML='<div style="position:fixed;left:18px;bottom:18px;width:min(420px,calc(100vw - 28px));border:1px solid rgba(255,255,255,.16);border-radius:20px;background:linear-gradient(180deg, rgba(6,28,36,.96), rgba(6,18,25,.94));box-shadow:0 28px 80px rgba(0,0,0,.52);padding:16px;color:#fff;pointer-events:auto"><div id="aeWg51Meta" class="pill">Step 1 / 1</div><h3 id="aeWg51Title" style="margin:8px 0 6px;font:700 18px system-ui"></h3><div id="aeWg51Body" style="font:13px system-ui;line-height:1.55;color:rgba(255,255,255,.84)"></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><button id="aeWg51Back">Back</button><button id="aeWg51Next">Next</button><div style="flex:1"></div><button id="aeWg51Close">Close</button></div></div>'; document.body.appendChild(overlay); document.getElementById('aeWg51Back').onclick=()=>move(-1); document.getElementById('aeWg51Next').onclick=()=>move(1); document.getElementById('aeWg51Close').onclick=()=>closeTour(); return overlay; }
  async function resolveTarget(step){ for(let i=0;i<10;i++){ const node = document.querySelector(step.selector); if(node) return node; await wait(90); } return null; }
  async function render(){ const step = steps[stepIndex]; if(step.before) await step.before(); clearTarget(); const target = await resolveTarget(step); if(target){ activeTarget = target; target.classList.add('ae-wg51-target'); target.scrollIntoView?.({ behavior:'smooth', block:'center', inline:'center' }); } ensureOverlay(); overlay.style.display='block'; document.getElementById('aeWg51Meta').textContent='Step '+(stepIndex+1)+' / '+steps.length; document.getElementById('aeWg51Title').textContent=step.title; document.getElementById('aeWg51Body').textContent=step.body; document.getElementById('aeWg51Back').disabled=stepIndex===0; document.getElementById('aeWg51Next').textContent=stepIndex===steps.length-1?'Finish':'Next'; }
  async function move(delta){ const next = stepIndex + delta; if(next < 0) return; if(next >= steps.length){ closeTour(); return; } stepIndex = next; await render(); }
  function closeTour(){ clearTarget(); if(overlay) overlay.style.display='none'; stepIndex = 0; }
  window.startAEWhiteGloveV51Tour = function(){ stepIndex = 0; render(); };
})();
