import fs from 'fs';
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';
import { execSync } from 'child_process';
import { createRequire } from 'module';
import { buildDirectiveMarkdown } from './update-directive.mjs';

function resolvePackRoot() {
  const cwd = process.cwd();
  const scriptDir = path.dirname(fileURLToPath(import.meta.url));
  const branchRootFromScript = path.resolve(scriptDir, '..');
  const launcherRootFromScript = path.resolve(branchRootFromScript, '..', '..');
  if (fs.existsSync(path.join(cwd, 'Branching Apps', 'AE-Brain-Command-Site-v8-Additive', 'index.html'))) return cwd;
  if (fs.existsSync(path.join(cwd, 'index.html')) && fs.existsSync(path.join(cwd, 'assets', 'app.js')) && path.basename(cwd) === 'AE-Brain-Command-Site-v8-Additive') return path.resolve(cwd, '..', '..');
  if (fs.existsSync(path.join(launcherRootFromScript, 'Branching Apps', 'AE-Brain-Command-Site-v8-Additive', 'index.html'))) return launcherRootFromScript;
  return cwd;
}

const require = createRequire(import.meta.url);
const packRoot = resolvePackRoot();
const root = path.resolve(packRoot, 'Branching Apps/AE-Brain-Command-Site-v8-Additive');
const core = await import(pathToFileURL(path.join(root, 'assets/core.mjs')).href);
const roster = JSON.parse(fs.readFileSync(path.join(root, 'data/ae-roster.json'), 'utf8'));
const source = JSON.parse(fs.readFileSync(path.join(root, 'docs/directive-source.json'), 'utf8'));
const checks = [];

function check(key, name, pass, detail) {
  checks.push({ key, name, pass, detail });
}

function fileIncludes(filePath, text) {
  return fs.readFileSync(filePath, 'utf8').includes(text);
}

const appJsPath = path.join(root, 'assets/app.js');
const stylesPath = path.join(root, 'assets/styles.css');
const indexPath = path.join(root, 'index.html');
const manifestPath = path.join(root, 'manifest.webmanifest');
const swPath = path.join(root, 'sw.js');
const directiveSourcePath = path.join(root, 'docs/directive-source.json');
const directivePath = path.join(root, 'docs/BUILD_DIRECTIVE.md');
const rootDirectivePath = path.join(packRoot, 'BUILD_DIRECTIVE_AE_BRAIN_COMMAND_SITE.md');
const launcherAppJsPath = path.join(packRoot, 'assets/app.js');
const aePackPagePath = path.join(packRoot, 'pages/ae-command-pack.html');
const netlifyRoot = path.join(packRoot, 'netlify/functions');
const dbSchemaPath = path.join(packRoot, 'db/ae_brain_command_site.sql');
const envExamplePath = path.join(packRoot, '.env.example');
const packageJsonPath = path.join(packRoot, 'package.json');
const netlifyTomlPath = path.join(packRoot, 'netlify.toml');
const deployRunbookPath = path.join(packRoot, 'docs/DEPLOY_RUNBOOK_AE_BRAIN_COMMAND_SITE.md');
const donorTemplateApiPath = path.join(netlifyRoot, 'ae-donor-template.js');
const compareApiPath = path.join(netlifyRoot, 'ae-brain-compare.js');
const smokeReportsApiPath = path.join(netlifyRoot, 'ae-brain-smoke-reports.js');
const donorTemplateSharedPath = path.join(netlifyRoot, '_shared/ae_donor_template.js');
const appointmentAdminHtmlPath = path.join(packRoot, 'Branching Apps/AI-Appointment-Setter-Brain-v33/static/admin/index.html');
const appointmentAdminJsPath = path.join(packRoot, 'Branching Apps/AI-Appointment-Setter-Brain-v33/static/js/admin.js');
const appointmentServerPath = path.join(packRoot, 'Branching Apps/AI-Appointment-Setter-Brain-v33/server.py');
const mediaVideoHelperPath = path.join(netlifyRoot, '_shared/media_center_video.js');
const mediaVideo = require(mediaVideoHelperPath);

check('branch-app-exists', 'branch app folder exists', fs.existsSync(root) && fs.existsSync(indexPath), 'Branch app and index are present');
check('offline-shell', 'offline shell exists', fs.existsSync(appJsPath) && fs.existsSync(stylesPath) && fileIncludes(indexPath, 'id="nav"') && fileIncludes(indexPath, 'id="view"'), 'Single page shell with nav and view host is present');
check('manifest-sw', 'manifest and service worker exist', fs.existsSync(manifestPath) && fs.existsSync(swPath), 'Offline install files are present');
check('roster-13', 'roster count is 13', roster.length === 13, `Roster length: ${roster.length}`);
const rosterFieldsOk = roster.every(item => item.name && item.title && item.lane && Array.isArray(item.specialties) && Array.isArray(item.clientTypes) && item.tone && item.headshotPrompt && item.systemPrompt && item.keySlot && 'enabled' in item);
check('ae-fields', 'AE roster fields are complete', rosterFieldsOk, 'Every AE contains role, prompt, caps, key slot, and enable metadata');
check('ae-toggle-caps', 'AE controls exist in UI', fileIncludes(appJsPath, 'toggle-ae') && fileIncludes(appJsPath, 'override-ae'), 'AE enable/disable and cap override controls are wired');
const state = core.defaultState(roster);
const demoClient = { id: 'client-1', name: 'Demo', company: 'Demo Co', tags: 'growth, infrastructure', needs: 'growth, infrastructure', clientType: 'growth', notes: 'Smoke demo', assignmentHistory: [] };
state.clients.push(demoClient);
const match = core.autoAssignClient(state, demoClient);
check('auto-routing', 'auto-assignment returns an AE', Boolean(match?.id), `Matched AE: ${match?.name || 'none'}`);
core.assignClient(state, demoClient.id, match.id, 'auto');
check('client-intake-ledger', 'client intake and ledger exist', fileIncludes(appJsPath, 'save-client') && fileIncludes(indexPath, 'AE Brain Command Site') && fileIncludes(appJsPath, 'client-history-panel'), 'Client intake and ledger panel are wired');
check('manual-reassign', 'assignment function supports manual mode', fileIncludes(appJsPath, 'Manual assign') && fileIncludes(appJsPath, "'manual'"), 'Manual assignment UI and mode string exist');
check('history-per-client', 'assignment history created', state.clients[0].assignmentHistory.length > 0, `History rows: ${state.clients[0].assignmentHistory.length}`);
check('export-json-csv', 'client export supports json and csv', fileIncludes(appJsPath, 'ae-brain-clients.json') && fileIncludes(appJsPath, 'ae-brain-clients.csv'), 'JSON and CSV export are both wired');
check('bulk-client-actions', 'bulk client action controls exist', fileIncludes(appJsPath, 'bulk-auto-assign') && fileIncludes(appJsPath, 'bulk-manual-assign') && fileIncludes(appJsPath, 'bulk-delete') && fileIncludes(appJsPath, 'select-all-visible'), 'Bulk select, assign, export, and delete controls are wired');
check('client-stage-priority', 'client stage and priority lane exists', fileIncludes(appJsPath, 'client-stage') && fileIncludes(appJsPath, 'client-priority') && fileIncludes(appJsPath, 'client-stage-filter') && fileIncludes(appJsPath, 'getClientStageCounts') && fileIncludes(appJsPath, 'getClientPriorityCounts'), 'Client stage/priority fields, filters, and dashboard helpers are wired');
check('client-dossier-links', 'client dossier with linked tasks and threads exists', fileIncludes(appJsPath, 'Linked tasks') && fileIncludes(appJsPath, 'Linked threads') && fileIncludes(appJsPath, 'create-client-task') && fileIncludes(appJsPath, 'create-client-thread'), 'Selected-client dossier includes linked work and quick create actions');
check('ae-rebalance', 'unavailable-ae rebalance exists', fileIncludes(appJsPath, 'rebalanceUnavailableAeClients') && fileIncludes(appJsPath, 'rebalance-unavailable-aes') && fileIncludes(appJsPath, 'ae-page-rebalance'), 'Client rebalance helper and UI actions are wired');
check('task-board', 'task board create and quick status movement exist', fileIncludes(appJsPath, 'save-task') && fileIncludes(appJsPath, 'task-status'), 'Task create and status quick-actions are wired');
check('transcript-thread-log', 'transcript thread creation exists', fileIncludes(appJsPath, 'save-thread') && fileIncludes(appJsPath, 'thread-message'), 'Thread creation and first-message capture are wired');
check('transcript-detail-reply', 'transcript reply flow exists', fileIncludes(appJsPath, 'save-thread-reply') && fileIncludes(appJsPath, 'thread-reply'), 'Transcript detail reply flow is wired');
check('transcript-search', 'transcript full-text search exists', fileIncludes(appJsPath, 'transcript-search') && fileIncludes(appJsPath, 'getTranscriptSearchResults') && fileIncludes(appJsPath, 'snippetAround'), 'Transcript search UI and message-text search logic are wired');
check('thread-export-promotion', 'thread export and promotion lane exists', fileIncludes(appJsPath, 'export-thread-json') && fileIncludes(appJsPath, 'export-thread-md') && fileIncludes(appJsPath, 'thread-to-task') && fileIncludes(appJsPath, 'function exportThread') && fileIncludes(appJsPath, 'function promoteThreadToTask'), 'Thread detail export and transcript-to-task controls are wired');
check('client-save-hardening', 'client save and bind hardening exists', fileIncludes(appJsPath, 'bindClientTableControls') && !fileIncludes(appJsPath, 'persistAeProfile(ae);\n    persistAeProfile(ae);') && fileIncludes(appJsPath, 'client-next-step'), 'Broken duplicate client-save path removed and row binding isolated from static controls');
check('directive-files', 'directive source and output files exist', fs.existsSync(directiveSourcePath), 'Directive source file exists for auto-generation');
check('smoke-script', 'smoke script exists', fs.existsSync(path.join(root, 'scripts/smoke.mjs')), 'Smoke script file present');
check('launcher-links', 'launcher links exist', (fileIncludes(launcherAppJsPath, 'AE-Brain-Command-Site-v8-Additive/index.html') || fileIncludes(aePackPagePath, 'AE-Brain-Command-Site-v8-Additive/index.html')), 'Launcher surface links into the branch app');
check('directive-autoupdater', 'directive auto-updater exists', fs.existsSync(path.join(root, 'scripts/update-directive.mjs')) && fileIncludes(path.join(root, 'scripts/update-directive.mjs'), 'buildDirectiveMarkdown'), 'Directive generator script is present');

const donorRoster = require(path.join(netlifyRoot, '_shared/ae_roster.js'));
const donorBrain = require(path.join(netlifyRoot, '_shared/ae_brain.js'));
const donorAuth = require(path.join(netlifyRoot, '_shared/ae_auth.js'));
check('donor-brain-runtime', 'donor brain runtime exists', donorRoster.AE_ROSTER.length === 13 && typeof donorBrain.callAeBrain === 'function', 'Shared donor brain runtime and replicated AE roster exist');
const allKeySlots = donorRoster.AE_ROSTER.map(item => item.keySlot);
check('thirteen-key-map', '13 key slots mapped', allKeySlots.every((slot, index) => slot === `AE_OPENAI_KEY_${String(index + 1).padStart(2, '0')}`), `Key slots: ${allKeySlots.join(', ')}`);
const samplePrompt = donorRoster.buildAeSystemPrompt(donorRoster.AE_ROSTER[0], { clientName: 'Demo Client', threadSubject: 'Launch plan' });
check('live-openai', 'live server brain files and prompt builder exist', fs.existsSync(path.join(netlifyRoot, 'ae-brain-chat.js')) && samplePrompt.includes('Demo Client') && fileIncludes(path.join(netlifyRoot, 'ae-brain-chat.js'), 'callAeBrain'), 'Server-side live brain chat lane exists and builds AE prompt context');
check('live-brain-console', 'live brain console exists in UI', fileIncludes(appJsPath, "'live-brain'") && fileIncludes(appJsPath, 'sendLiveBrainMessage') && fileIncludes(appJsPath, '/.netlify/functions/ae-brain-chat'), 'Live Brain tab and sender are wired');
check('live-brain-health', 'live brain health route exists', fs.existsSync(path.join(netlifyRoot, 'ae-brain-health.js')), 'Health route file exists');
const signed = donorAuth.mintSession({ email: 'founder@example.com', exp: Date.now() + 60000 }, 'smoke-secret');
const verified = donorAuth.verifySession(signed, 'smoke-secret');
check('founder-auth', 'founder auth helpers exist', Boolean(verified?.email === 'founder@example.com') && fs.existsSync(path.join(netlifyRoot, 'ae-founder-login.js')) && fs.existsSync(path.join(netlifyRoot, 'ae-founder-logout.js')), 'Founder session signing/verifying helpers and auth routes exist');
check('shared-db', 'shared database state lane files exist', fs.existsSync(path.join(netlifyRoot, 'ae-branch-state.js')) && fs.existsSync(dbSchemaPath) && fileIncludes(path.join(netlifyRoot, 'ae-branch-state.js'), 'saveStateSnapshot'), 'Shared branch state sync API and schema are present');
check('serverless-apis', 'root serverless api set exists', ['ae-founder-login.js','ae-founder-me.js','ae-founder-logout.js','ae-branch-state.js','ae-brain-chat.js','ae-brain-health.js'].every(file => fs.existsSync(path.join(netlifyRoot, file))), 'Auth, state, chat, and health serverless routes are present');
check('real-usage-metering', 'usage metering write lane exists', fileIncludes(path.join(netlifyRoot, '_shared/ae_state.js'), 'insert into ae_branch_usage_events') && fileIncludes(path.join(netlifyRoot, 'ae-brain-chat.js'), 'writeUsageEvent'), 'Usage write path exists in shared state helper and chat route');
check('db-schema-live-lane', 'db schema exists for live lane', fs.existsSync(dbSchemaPath) && fileIncludes(dbSchemaPath, 'ae_branch_state') && fileIncludes(dbSchemaPath, 'ae_branch_usage_events'), 'Database schema contains branch state and usage tables');

check('live-streaming-sse', 'stream endpoint and UI streaming lane exist', fs.existsSync(path.join(netlifyRoot, 'ae-brain-stream.js')) && fileIncludes(appJsPath, 'live-stream') && fileIncludes(appJsPath, 'streamLiveBrainMessage') && fileIncludes(path.join(netlifyRoot, 'ae-brain-stream.js'), 'text/event-stream'), 'Stream endpoint, UI checkbox, and stream parser are wired');
check('multi-founder-rbac', 'multi-user RBAC lane exists', fs.existsSync(path.join(netlifyRoot, 'ae-access-users.js')) && fs.existsSync(path.join(netlifyRoot, '_shared/ae_users.js')) && fileIncludes(path.join(netlifyRoot, '_shared/ae_auth.js'), 'requireRole') && fileIncludes(appJsPath, "'access'"), 'Access tab, user store, and role guard helpers are present');
check('normalized-resource-apis', 'normalized per-resource APIs exist', ['ae-clients.js','ae-tasks.js','ae-threads.js','ae-messages.js','ae-assignments.js','ae-access-users.js'].every(file => fs.existsSync(path.join(netlifyRoot, file))) && fs.existsSync(path.join(netlifyRoot, '_shared/ae_resources.js')) && fileIncludes(appJsPath, 'tryLoadRemoteResources') && fileIncludes(appJsPath, "remoteUpsert('clients'"), 'Per-resource routes, shared resource helper, and UI remote resource sync are present');
check('multi-vendor-provider-failover', 'multi-provider failover exists', fs.existsSync(path.join(netlifyRoot, '_shared/ae_providers.js')) && fileIncludes(path.join(netlifyRoot, '_shared/ae_brain.js'), "['anthropic', 'gemini']") && fileIncludes(path.join(packRoot, '.env.example'), 'ANTHROPIC_API_KEY=') && fileIncludes(path.join(packRoot, '.env.example'), 'GEMINI_API_KEY='), 'OpenAI primary plus Anthropic and Gemini fallback-ready runtime exists');
check('remote-roster-override-api', 'remote roster override api exists', fs.existsSync(path.join(netlifyRoot, 'ae-brains.js')) && fs.existsSync(path.join(netlifyRoot, '_shared/ae_brain_overrides.js')) && fileIncludes(appJsPath, '/.netlify/functions/ae-brains') && fileIncludes(path.join(netlifyRoot, '_shared/ae_brain.js'), 'getMergedAeProfile'), 'AE roster override route, helper, UI hook, and merged runtime are present');
check('remote-usage-summary-api', 'remote usage summary api exists', fs.existsSync(path.join(netlifyRoot, 'ae-usage-summary.js')) && fileIncludes(path.join(netlifyRoot, '_shared/ae_state.js'), 'listUsageSummary') && fileIncludes(appJsPath, '/.netlify/functions/ae-usage-summary'), 'Usage summary route, query helper, and dashboard hook are present');
check('remote-audit-events-api', 'remote audit events api exists', fs.existsSync(path.join(netlifyRoot, 'ae-audit-events.js')) && fileIncludes(path.join(netlifyRoot, '_shared/ae_state.js'), 'listAuditEvents') && fileIncludes(appJsPath, '/.netlify/functions/ae-audit-events'), 'Audit events route, query helper, and dashboard hook are present');
check('deploy-ops-files', 'deploy ops files exist', fs.existsSync(packageJsonPath) && fs.existsSync(netlifyTomlPath) && fs.existsSync(deployRunbookPath) && fs.existsSync(envExamplePath) && fileIncludes(envExamplePath, 'AE_OPENAI_MODEL_01='), 'Package scripts, Netlify config, deploy runbook, and richer env example are present');
check('batch-live-smoke', 'batch live smoke route and UI exist', fs.existsSync(path.join(netlifyRoot, 'ae-brain-smoke.js')) && fileIncludes(appJsPath, 'run-live-smoke') && fileIncludes(appJsPath, '/.netlify/functions/ae-brain-smoke'), 'Batch live smoke route and UI controls are wired');
check('ae-runtime-editor', 'AE runtime editor exists', fileIncludes(appJsPath, 'save-ae-runtime') && fileIncludes(appJsPath, 'data-ae-provider') && fileIncludes(appJsPath, 'persistAeProfile'), 'Per-AE runtime provider/model/failover editor exists');
check('donor-template-api', 'donor runtime template api exists', fs.existsSync(donorTemplateApiPath) && fs.existsSync(donorTemplateSharedPath) && fileIncludes(appJsPath, 'save-donor-template') && fileIncludes(appJsPath, '/.netlify/functions/ae-donor-template'), 'Donor template api, shared helper, and branch UI save hook are present');
check('responses-mode', 'responses-mode donor runtime exists', fileIncludes(path.join(netlifyRoot, '_shared/ae_providers.js'), '/v1/responses') && fileIncludes(donorTemplateSharedPath, 'endpointMode') && fileIncludes(appJsPath, 'responses'), 'OpenAI Responses-mode support is present in the shared donor runtime and branch UI');
check('brain-compare-matrix', 'multi-ae compare matrix exists', fs.existsSync(compareApiPath) && fileIncludes(appJsPath, 'run-brain-compare') && fileIncludes(appJsPath, 'export-compare-results') && fileIncludes(appJsPath, 'compare-ae'), 'Compare api and multi-AE compare controls are wired');
check('smoke-report-history', 'smoke report history exists', fs.existsSync(smokeReportsApiPath) && fileIncludes(path.join(netlifyRoot, '_shared/ae_state.js'), 'ae_branch_smoke_reports') && fileIncludes(appJsPath, 'refresh-smoke-reports') && fileIncludes(appJsPath, 'load-smoke-report'), 'Smoke report table, listing api, and branch UI report loader are present');

check('access-user-admin-actions', 'access user admin actions exist', fileIncludes(appJsPath, 'toggle-user-status') && fileIncludes(appJsPath, 'delete-user') && fileIncludes(path.join(netlifyRoot, 'ae-access-users.js'), "event.httpMethod === 'PATCH'") && fileIncludes(path.join(netlifyRoot, '_shared/ae_users.js'), 'async function updateUser'), 'Access user enable/disable/delete actions are wired');

check('client-followup-queue', 'client follow-up queue exists', fileIncludes(appJsPath, 'client-follow-up') && fileIncludes(appJsPath, 'getFollowupQueue') && fileIncludes(appJsPath, 'Follow-up queue') && fileIncludes(appJsPath, 'Follow-ups overdue'), 'Follow-up date field, dashboard queue, and due-count helpers are wired');
check('client-duplicate-watch', 'client duplicate watch exists', fileIncludes(appJsPath, 'findPotentialDuplicateClients') && fileIncludes(appJsPath, 'client-duplicate-watch') && fileIncludes(appJsPath, 'Possible duplicate clients found'), 'Duplicate detection helper, intake panel, and pre-save warning are wired');
check('client-filter-presets', 'client filter presets exist', fileIncludes(appJsPath, 'save-client-filter-preset') && fileIncludes(appJsPath, 'loadClientFilterPreset') && fileIncludes(appJsPath, 'deleteClientFilterPreset') && fileIncludes(path.join(root, 'assets/core.mjs'), 'clientFilterPresets'), 'Client filter preset state, load, save, and delete controls are wired');
check('client-activity-timeline', 'client activity timeline and dossier export exist', fileIncludes(appJsPath, 'buildClientActivityTimeline') && fileIncludes(appJsPath, 'Activity timeline') && fileIncludes(appJsPath, 'export-client-md') && fileIncludes(appJsPath, 'exportClientDossier'), 'Client dossier timeline and JSON/Markdown export helpers are wired');
check('client-match-insights', 'client ranked ae match insights exist', fileIncludes(appJsPath, 'Top AE candidates') && fileIncludes(appJsPath, 'getAeMatchCandidates') && fileIncludes(path.join(root, 'assets/core.mjs'), 'rankAeCandidates'), 'Ranked AE candidate helper and dossier match insights are wired');


check('bind-view-dispatch', 'page-level bind dispatcher exists', fileIncludes(appJsPath, 'function bindView') && fileIncludes(appJsPath, "if (page === 'dashboard') bindDashboard()") && fileIncludes(appJsPath, "if (page === 'clients') bindClients()") && fileIncludes(appJsPath, "if (page === 'live-brain') bindLiveBrain()"), 'Rendered pages now dispatch their control binders after each render pass');
check('client-edit-mode', 'client edit mode exists', fileIncludes(appJsPath, 'editingClientId') && fileIncludes(appJsPath, 'client-form-mode') && fileIncludes(appJsPath, 'cancel-client-edit') && fileIncludes(appJsPath, 'Update client') && fileIncludes(appJsPath, 'loadClientIntoForm'), 'Client form supports edit mode, update-save, and cancel-edit controls');
check('client-bulk-stage-priority', 'bulk client stage and priority update exists', fileIncludes(appJsPath, 'bulk-stage-select') && fileIncludes(appJsPath, 'bulk-update-stage') && fileIncludes(appJsPath, 'bulk-priority-select') && fileIncludes(appJsPath, 'bulk-update-priority') && fileIncludes(appJsPath, 'bulkUpdateSelectedStage') && fileIncludes(appJsPath, 'bulkUpdateSelectedPriority'), 'Selected clients can receive bulk stage and priority changes');
check('client-followup-quick-actions', 'follow-up quick actions exist', fileIncludes(appJsPath, 'followup-snooze-1') && fileIncludes(appJsPath, 'followup-snooze-7') && fileIncludes(appJsPath, 'followup-complete') && fileIncludes(appJsPath, 'client-snooze-1d') && fileIncludes(appJsPath, 'client-followup-complete') && fileIncludes(appJsPath, 'completeClientFollowUp'), 'Dashboard queue and client dossier include one-click follow-up snooze and completion actions');

check('task-due-analytics', 'task due analytics and dashboard queue exist', fileIncludes(appJsPath, 'getTaskDueCounts') && fileIncludes(appJsPath, 'getTaskQueue') && fileIncludes(appJsPath, 'Task due queue') && fileIncludes(appJsPath, 'dashboard-open-task') && fileIncludes(appJsPath, 'task-snooze-1') && fileIncludes(appJsPath, 'task-complete'), 'Dashboard includes task due-state counts and actionable task queue controls');
check('task-edit-mode', 'task edit mode exists', fileIncludes(appJsPath, 'editingTaskId') && fileIncludes(appJsPath, 'task-form-mode') && fileIncludes(appJsPath, 'cancel-task-edit') && fileIncludes(appJsPath, 'Update task') && fileIncludes(appJsPath, 'loadTaskIntoForm'), 'Task form supports edit mode, update-save, and cancel-edit controls');
check('task-filters', 'task search and filter controls exist', fileIncludes(appJsPath, 'task-search') && fileIncludes(appJsPath, 'task-status-filter') && fileIncludes(appJsPath, 'task-ae-filter') && fileIncludes(appJsPath, 'task-client-filter') && fileIncludes(appJsPath, 'task-due-filter') && fileIncludes(appJsPath, 'getFilteredTasks'), 'Task board includes query, status, AE, client, and due-state filtering');
check('transcript-thread-state', 'transcript thread state controls exist', fileIncludes(appJsPath, 'transcript-state-filter') && fileIncludes(appJsPath, 'thread-toggle-pin') && fileIncludes(appJsPath, 'thread-toggle-state') && fileIncludes(appJsPath, 'thread-pin-toggle') && fileIncludes(appJsPath, 'thread-state-toggle'), 'Transcript list and detail include pin, resolve, reopen, and state filtering controls');
check('task-bulk-ops', 'task bulk operations exist', fileIncludes(appJsPath, 'select-all-visible-tasks') && fileIncludes(appJsPath, 'bulk-update-task-status') && fileIncludes(appJsPath, 'bulk-task-snooze-1') && fileIncludes(appJsPath, 'bulk-export-tasks') && fileIncludes(appJsPath, 'bulk-delete-tasks') && fileIncludes(appJsPath, 'bindTaskSelectionControls') && fileIncludes(appJsPath, 'bulkUpdateSelectedTasksStatus'), 'Task board includes selection, bulk status, snooze, export, and delete controls');
check('task-filter-presets', 'task filter presets exist', fileIncludes(appJsPath, 'save-task-filter-preset') && fileIncludes(appJsPath, 'loadTaskFilterPreset') && fileIncludes(appJsPath, 'deleteTaskFilterPreset') && fileIncludes(path.join(root, 'assets/core.mjs'), 'taskFilterPresets'), 'Task filter preset state plus save/load/delete controls are wired');
check('followup-task-automation', 'follow-up to task automation exists', fileIncludes(appJsPath, 'createFollowupTaskFromClient') && fileIncludes(appJsPath, 'followup-to-task') && fileIncludes(appJsPath, 'create-client-followup-task') && fileIncludes(appJsPath, 'bulk-create-followup-tasks'), 'Dashboard queue, client dossier, and bulk client controls can convert follow-up work into tasks');
check('ops-snapshot-export', 'ops snapshot export exists', fileIncludes(appJsPath, 'buildOperationalSnapshot') && fileIncludes(appJsPath, 'exportOperationalSnapshot') && fileIncludes(appJsPath, 'export-ops-snapshot-json') && fileIncludes(appJsPath, 'export-ops-snapshot-md'), 'Dashboard exports founder-readable operational snapshots in JSON and Markdown');
check('client-health-lane', 'client health scoring and filtering exist', fileIncludes(appJsPath, 'getClientHealth') && fileIncludes(appJsPath, 'getClientHealthCounts') && fileIncludes(appJsPath, 'client-health-filter') && fileIncludes(appJsPath, 'Client health') && fileIncludes(appJsPath, 'health ${escapeHtml(health.label)}'), 'Client health helpers, filter control, and dossier/dashboard indicators are wired');
check('at-risk-dashboard-queue', 'at-risk dashboard queue exists', fileIncludes(appJsPath, 'At-risk client queue') && fileIncludes(appJsPath, 'risk-open-client') && fileIncludes(appJsPath, 'risk-create-plan') && fileIncludes(appJsPath, 'getAtRiskClients'), 'Dashboard surfaces at-risk clients with open and action-plan controls');
check('task-template-library', 'task template library exists', fileIncludes(appJsPath, 'TASK_TEMPLATE_LIBRARY') && fileIncludes(appJsPath, 'task-template-select') && fileIncludes(appJsPath, 'applyTaskTemplateToForm') && fileIncludes(appJsPath, 'createTaskFromTemplate'), 'Task template constants plus task-form apply/create controls are wired');
check('client-action-plan-automation', 'client action plan automation exists', fileIncludes(appJsPath, 'CLIENT_ACTION_PLAN_LIBRARY') && fileIncludes(appJsPath, 'createClientActionPlan') && fileIncludes(appJsPath, 'client-plan-select') && fileIncludes(appJsPath, 'bulk-create-client-plans'), 'Client dossier, dashboard, and bulk client controls can create sequenced action-plan tasks');
check('transcript-stale-queue', 'stale transcript queue exists', fileIncludes(appJsPath, 'getThreadFreshness') && fileIncludes(appJsPath, 'getStaleThreads') && fileIncludes(appJsPath, 'Transcript stale queue') && fileIncludes(appJsPath, 'stale-thread-task') && fileIncludes(appJsPath, 'stale-thread-resolve') && fileIncludes(appJsPath, "'stale'"), 'Transcript freshness helpers, stale queue, stale filtering, and response-task controls are wired');
check('client-recommendation-engine', 'client recommendation engine exists', fileIncludes(appJsPath, 'getClientRecommendedActions') && fileIncludes(appJsPath, 'applyClientRecommendation') && fileIncludes(appJsPath, 'Recommended actions') && fileIncludes(appJsPath, 'client-recommendation'), 'Client dossier surfaces recommendation actions with apply controls and automation handlers');
check('ae-workload-alerts', 'AE workload alert queue exists', fileIncludes(appJsPath, 'getAeWorkloadAlerts') && fileIncludes(appJsPath, 'AE workload alerts') && fileIncludes(appJsPath, 'workload-open-clients') && fileIncludes(appJsPath, 'workload-rebalance-ae'), 'AE workload alert helpers and dashboard rebalance/open-client controls are wired');
check('command-brief-export', 'command brief export exists', fileIncludes(appJsPath, 'buildCommandBrief') && fileIncludes(appJsPath, 'exportCommandBrief') && fileIncludes(appJsPath, 'export-command-brief-json') && fileIncludes(appJsPath, 'ae-command-brief.md'), 'Command brief JSON/Markdown export covering stale threads, workload, and recommendations is wired');
check('response-playbook-library', 'response playbook library exists', fileIncludes(appJsPath, 'RESPONSE_PLAYBOOK_LIBRARY') && fileIncludes(appJsPath, 'thread-playbook-select') && fileIncludes(appJsPath, 'thread-playbook-apply') && fileIncludes(appJsPath, 'thread-playbook-save') && fileIncludes(appJsPath, 'applyResponsePlaybookToThread') && fileIncludes(appJsPath, 'stale-playbook-followup'), 'Transcript playbook constants plus insert/save controls are wired from thread detail and stale-thread handling');
check('client-sla-pressure', 'client sla pressure helpers and dashboard queue exist', fileIncludes(appJsPath, 'getClientSlaPressure') && fileIncludes(appJsPath, 'getSlaPressureCounts') && fileIncludes(appJsPath, 'SLA pressure queue') && fileIncludes(appJsPath, 'sla-open-client') && fileIncludes(appJsPath, 'sla-create-plan'), 'Client SLA scoring, counts, and dashboard queue actions are wired');
check('task-blocker-lane', 'task blocker lane exists', fileIncludes(appJsPath, 'task-status-form') && fileIncludes(appJsPath, 'task-blocker-note') && fileIncludes(appJsPath, 'getTaskBlockedCounts') && fileIncludes(appJsPath, 'Blocked task queue') && fileIncludes(appJsPath, 'blocked-task-escalate') && fileIncludes(appJsPath, 'blocked-task-unblock'), 'Blocked status, blocker note, blocked-task queues, and escalation/unblock controls are wired');
check('sla-brief-export', 'sla brief export exists', fileIncludes(appJsPath, 'buildSlaBrief') && fileIncludes(appJsPath, 'exportSlaBrief') && fileIncludes(appJsPath, 'export-sla-brief-json') && fileIncludes(appJsPath, 'ae-sla-brief.md'), 'SLA brief JSON/Markdown export covering pressure queue, blocked tasks, and stale threads is wired');
check('response-waiting-queue', 'response-waiting queue exists', fileIncludes(appJsPath, 'getThreadResponseLag') && fileIncludes(appJsPath, 'getAwaitingResponseThreads') && fileIncludes(appJsPath, 'Response waiting queue') && fileIncludes(appJsPath, 'awaiting-open-thread') && fileIncludes(appJsPath, 'awaiting-playbook') && fileIncludes(appJsPath, 'awaiting-response-task'), 'Dashboard queue, helpers, and transcript awaiting filter are wired for unanswered inbound threads');
check('ae-performance-brief', 'ae performance scorecard exists', fileIncludes(appJsPath, 'buildAePerformanceRows') && fileIncludes(appJsPath, 'exportAePerformanceBrief') && fileIncludes(appJsPath, 'AE performance scorecard') && fileIncludes(appJsPath, 'export-ae-performance-json') && fileIncludes(appJsPath, 'performance-open-clients'), 'AE pressure scorecard and export controls are wired');
check('task-dependency-lane', 'task dependency lane exists', fileIncludes(appJsPath, 'getTaskDependency') && fileIncludes(appJsPath, 'syncTaskDependencyState') && fileIncludes(appJsPath, 'task-dependency') && fileIncludes(appJsPath, 'Dependency queue') && fileIncludes(appJsPath, 'task-resume-dependency') && fileIncludes(appJsPath, 'dependency-open-task'), 'Task dependency selection, waiting state, queue, and resume controls are wired');
check('client-handoff-brief', 'client handoff brief exists', fileIncludes(appJsPath, 'buildClientHandoffBrief') && fileIncludes(appJsPath, 'exportClientHandoffBrief') && fileIncludes(appJsPath, 'client-handoff-note') && fileIncludes(appJsPath, 'export-client-handoff-json') && fileIncludes(appJsPath, 'ae-client-handoff.md'), 'Client handoff note capture and JSON/Markdown handoff export are wired');
check('task-recurrence-lane', 'task recurrence lane exists', fileIncludes(appJsPath, 'TASK_RECURRENCE_OPTIONS') && fileIncludes(appJsPath, 'task-recurrence') && fileIncludes(appJsPath, 'spawnRecurringTaskIfNeeded') && fileIncludes(appJsPath, 'getRecurringTaskQueue') && fileIncludes(appJsPath, 'Recurring task queue'), 'Recurring task cadence field, spawn helper, queue, and recurrence-aware controls are wired');
check('client-contact-cadence', 'client contact cadence and no-contact queue exist', fileIncludes(appJsPath, 'getClientTouchStatus') && fileIncludes(appJsPath, 'getClientTouchCounts') && fileIncludes(appJsPath, 'client-touch-filter') && fileIncludes(appJsPath, 'No-contact queue') && fileIncludes(appJsPath, 'no-contact-task'), 'Client touch scoring, filters, dashboard queue, and nudge task controls are wired');
check('thread-draft-autosave', 'thread draft autosave and restore lane exists', fileIncludes(appJsPath, 'persistThreadDraft') && fileIncludes(appJsPath, 'clearThreadDraft') && fileIncludes(appJsPath, 'Reply draft queue') && fileIncludes(appJsPath, 'draft-open-thread') && fileIncludes(appJsPath, 'clear-thread-draft'), 'Transcript drafts autosave while typing and surface through a dedicated restore/clear queue');
check('cadence-brief-export', 'cadence brief export exists', fileIncludes(appJsPath, 'buildCadenceBrief') && fileIncludes(appJsPath, 'exportCadenceBrief') && fileIncludes(appJsPath, 'export-cadence-brief-json') && fileIncludes(appJsPath, 'ae-cadence-brief.md'), 'Cadence brief JSON/Markdown export covering no-contact clients, recurring load, and reply drafts is wired');
check('client-milestone-lane', 'client milestone tracking lane exists', fileIncludes(appJsPath, 'getClientMilestoneState') && fileIncludes(appJsPath, 'client-milestone') && fileIncludes(appJsPath, 'Milestone queue') && fileIncludes(appJsPath, 'milestone-progress') && fileIncludes(appJsPath, 'client-milestone-clear'), 'Client milestone fields, queue, and quick-advance controls are wired');
check('task-effort-lane', 'task effort tracking lane exists', fileIncludes(appJsPath, 'getTaskEffortState') && fileIncludes(appJsPath, 'task-estimated-minutes') && fileIncludes(appJsPath, 'Task effort queue') && fileIncludes(appJsPath, 'task-add-effort') && fileIncludes(appJsPath, 'Estimated minutes'), 'Task effort fields, dashboard queue, inline time logging, and effort exports are wired');
check('thread-summary-lane', 'thread summary lane exists', fileIncludes(appJsPath, 'saveThreadSummary') && fileIncludes(appJsPath, 'thread-summary') && fileIncludes(appJsPath, 'Open question queue') && fileIncludes(appJsPath, 'save-thread-summary') && fileIncludes(appJsPath, 'clear-thread-summary'), 'Thread summary capture, open-question queue, and save/clear controls are wired');
check('daily-focus-brief', 'daily focus brief export exists', fileIncludes(appJsPath, 'buildDailyFocusBrief') && fileIncludes(appJsPath, 'exportDailyFocusBrief') && fileIncludes(appJsPath, 'export-daily-focus-json') && fileIncludes(appJsPath, 'ae-daily-focus-brief.md'), 'Daily focus brief JSON/Markdown export covering milestones, effort, and open questions is wired');
check('alert-inbox-lane', 'unified alert inbox lane exists', fileIncludes(appJsPath, 'getAlertInbox') && fileIncludes(appJsPath, 'renderAlertInboxCard') && fileIncludes(appJsPath, 'alert-open-client') && fileIncludes(appJsPath, 'alert-open-thread') && fileIncludes(appJsPath, 'alert-open-task') && fileIncludes(appJsPath, 'alert-ack') && fileIncludes(appJsPath, 'alert-snooze-7'), 'Unified alert inbox with acknowledge/snooze/open controls is wired');
check('alert-digest-export', 'alert digest export exists', fileIncludes(appJsPath, 'buildAlertDigest') && fileIncludes(appJsPath, 'exportAlertDigest') && fileIncludes(appJsPath, 'export-alert-digest-json') && fileIncludes(appJsPath, 'ae-alert-digest.md'), 'Alert digest JSON/Markdown export for active unified alerts is wired');
check('brief-archive-history', 'brief archive history exists', fileIncludes(appJsPath, 'saveBriefArchive') && fileIncludes(appJsPath, 'renderBriefArchiveCard') && fileIncludes(appJsPath, 'save-brief-archive') && fileIncludes(appJsPath, 'brief-export-json') && fileIncludes(appJsPath, 'brief-delete'), 'Saved brief archive with save/export/delete controls is wired');
check('audit-command-center', 'audit command center exists', fileIncludes(appJsPath, 'renderAuditCommandCenter') && fileIncludes(appJsPath, 'getCombinedAuditRows') && fileIncludes(appJsPath, 'audit-search') && fileIncludes(appJsPath, 'exportAuditDigest') && fileIncludes(appJsPath, 'ae-audit-digest.md'), 'Merged local/remote audit command center with filters and exports is wired');

check('client-revenue-pipeline', 'client revenue pipeline lane exists', fileIncludes(appJsPath, 'client-estimated-value') && fileIncludes(appJsPath, 'client-monthly-value') && fileIncludes(appJsPath, 'client-close-probability') && fileIncludes(appJsPath, 'client-target-close') && fileIncludes(appJsPath, 'client-value-filter') && fileIncludes(appJsPath, 'buildRevenueBrief') && fileIncludes(appJsPath, 'ae-revenue-brief.md'), 'Client revenue fields, value-tier filtering, and revenue export are wired');
check('ae-availability-planner', 'AE availability planner exists', fileIncludes(appJsPath, 'data-ae-availability') && fileIncludes(appJsPath, 'data-ae-until') && fileIncludes(appJsPath, 'data-ae-note') && fileIncludes(appJsPath, 'getAeAvailabilityState') && fileIncludes(path.join(root, 'assets/core.mjs'), 'availabilityState') && fileIncludes(path.join(root, 'assets/core.mjs'), 'backupOnly'), 'AE availability controls and routing-aware availability scoring are wired');
check('dashboard-revenue-forecast', 'dashboard revenue forecast and coverage planner exist', fileIncludes(appJsPath, 'Revenue forecast') && fileIncludes(appJsPath, 'Coverage planner') && fileIncludes(appJsPath, 'Weighted pipeline') && fileIncludes(appJsPath, 'getSevenDayCommandPlan'), 'Dashboard weighted pipeline, coverage alerts, and next-7-day planner cards are wired');
check('command-planner-brief', 'command planner brief exports exist', fileIncludes(appJsPath, 'buildCommandPlannerBrief') && fileIncludes(appJsPath, 'exportCommandPlannerBrief') && fileIncludes(appJsPath, 'ae-command-planner-brief.md') && fileIncludes(appJsPath, 'export-command-planner-json'), 'Revenue brief and 7-day planner JSON/Markdown export lanes are wired');
check('pipeline-board-lane', 'pipeline board lane exists', fileIncludes(appJsPath, 'getPipelineBoardData') && fileIncludes(appJsPath, 'renderPipelineBoardCard') && fileIncludes(appJsPath, 'pipeline-stage-forward') && fileIncludes(appJsPath, 'pipeline-stage-back') && fileIncludes(appJsPath, 'ae-pipeline-board-brief.md') && fileIncludes(appJsPath, 'export-pipeline-brief-json'), 'Stage-weighted pipeline board, quick stage movement, and JSON/Markdown pipeline export are wired');
check('rebalancer-planner-lane', 'coverage rebalancer planner exists', fileIncludes(appJsPath, 'buildRebalancePlanner') && fileIncludes(appJsPath, 'renderRebalancePlannerCard') && fileIncludes(appJsPath, 'rebalance-apply-one') && fileIncludes(appJsPath, 'rebalance-apply-all') && fileIncludes(appJsPath, 'ae-rebalance-plan-brief.md') && fileIncludes(appJsPath, 'export-rebalance-brief-json'), 'Suggested rebalance moves, one-click apply controls, and JSON/Markdown rebalance export are wired');
check('command-calendar-lane', '14-day command calendar exists', fileIncludes(appJsPath, 'getFourteenDayCommandCalendar') && fileIncludes(appJsPath, 'renderCommandCalendarCard') && fileIncludes(appJsPath, 'calendar-open-client') && fileIncludes(appJsPath, 'calendar-open-task') && fileIncludes(appJsPath, 'ae-command-calendar-brief.md') && fileIncludes(appJsPath, 'export-command-calendar-json'), '14-day command calendar for follow-ups, milestones, tasks, close targets, and AE coverage checkpoints is wired');
check('ae-ownership-brief', 'AE ownership board and brief exist', fileIncludes(appJsPath, 'buildAeOwnershipRows') && fileIncludes(appJsPath, 'renderAeOwnershipCard') && fileIncludes(appJsPath, 'ownership-open-clients') && fileIncludes(appJsPath, 'ae-ownership-brief.md') && fileIncludes(appJsPath, 'export-ownership-brief-json'), 'AE ownership board with revenue, follow-up burden, and JSON/Markdown export is wired');


check('automation-engine-lane', 'automation engine lane exists', fileIncludes(appJsPath, 'buildAutomationDigest') && fileIncludes(appJsPath, 'runAutomationRule') && fileIncludes(appJsPath, 'run-all-automations') && fileIncludes(appJsPath, 'toggle-automation-rule') && fileIncludes(path.join(root, 'assets/core.mjs'), 'automationRules'), 'Automation rules, digest export, run controls, and state lanes are wired');
check('restore-point-lane', 'restore point lane exists', fileIncludes(appJsPath, 'saveRestorePoint') && fileIncludes(appJsPath, 'restoreFromPoint') && fileIncludes(appJsPath, 'restore-point-restore') && fileIncludes(path.join(root, 'assets/core.mjs'), 'restorePoints'), 'Restore point save/restore/export controls and state lane are wired');
check('workspace-preset-lane', 'workspace preset lane exists', fileIncludes(appJsPath, 'saveWorkspacePreset') && fileIncludes(appJsPath, 'loadWorkspacePreset') && fileIncludes(appJsPath, 'save-workspace-preset') && fileIncludes(path.join(root, 'assets/core.mjs'), 'workspacePresets'), 'Workspace preset save/load/delete controls and state lane are wired');
check('command-macro-lane', 'command macro lane exists', fileIncludes(appJsPath, 'COMMAND_MACRO_LIBRARY') && fileIncludes(appJsPath, 'runCommandMacro') && fileIncludes(appJsPath, 'run-command-macro') && fileIncludes(path.join(root, 'assets/core.mjs'), 'macroRuns'), 'Command macro library, run controls, and macro run history lane are wired');
check('appointment-bridge-state', 'appointment bridge state lane exists', fileIncludes(appJsPath, 'ensureAppointmentBridge') && fileIncludes(appJsPath, 'appointmentBridge') && fileIncludes(path.join(root, 'assets/core.mjs'), 'appointmentBridge') && fileIncludes(appJsPath, 'loadAppointmentDonorRuntimeSeed'), 'Appointment bridge state, donor runtime seed, and canonical handoff lane are wired');
check('appointment-command-surface', 'appointment brain command surface exists', fileIncludes(appJsPath, "'appointment-brain'") && fileIncludes(appJsPath, 'renderAppointmentBrain') && fileIncludes(appJsPath, 'createAppointmentFromHandoff') && fileIncludes(appJsPath, 'returnAppointmentClientToAe') && fileIncludes(appJsPath, 'Launch donor admin'), 'Appointment brain page, booking board, return-to-AE controls, and donor admin launch are wired');
check('client-appointment-controls', 'client appointment handoff controls exist', fileIncludes(appJsPath, 'bulk-send-to-appointment') && fileIncludes(appJsPath, 'send-client-to-appointment') && fileIncludes(appJsPath, 'book-client-appointment') && fileIncludes(appJsPath, 'Appointment brain</div>'), 'Bulk handoff, dossier handoff/book controls, and appointment history in the client dossier are wired');
check('omega-brief-export', 'appointment and 0mega brief export exists', fileIncludes(appJsPath, 'exportAppointmentBridgeBrief') && fileIncludes(appJsPath, 'exportOmegaCommandBrief') && fileIncludes(appJsPath, 'ae-appointment-bridge-brief.md') && fileIncludes(appJsPath, 'ae-omega-command-brief.md'), 'Appointment brief and combined 0mega brief JSON/Markdown export lanes are wired');
check('donor-bridge-api', 'donor admin bridge panel and APIs exist', fileIncludes(appointmentAdminHtmlPath, 'AE command bridge') && fileIncludes(appointmentAdminJsPath, 'importAeBridgePayload') && fileIncludes(appointmentAdminJsPath, 'exportAeBridgePayload') && fileIncludes(appointmentServerPath, '/api/admin/ae-bridge') && fileIncludes(appointmentServerPath, '_import_ae_bridge_payload'), 'Donor admin bridge panel plus import/export server endpoints are wired');


check('appointment-sequence-engine', 'appointment sequence engine exists', fileIncludes(appJsPath, 'APPOINTMENT_SEQUENCE_LIBRARY') && fileIncludes(appJsPath, 'enrollAppointmentSequence') && fileIncludes(appJsPath, 'advanceAppointmentSequence') && fileIncludes(appJsPath, 'renderAppointmentSequenceCard') && fileIncludes(path.join(root, 'assets/core.mjs'), 'sequences'), 'Appointment sequence templates, queue, advance controls, and state lane are wired');
check('appointment-slot-planner', 'appointment slot planner and conflict repair exist', fileIncludes(appJsPath, 'APPOINTMENT_SLOT_TEMPLATE_LIBRARY') && fileIncludes(appJsPath, 'getAppointmentConflictQueue') && fileIncludes(appJsPath, 'buildAppointmentSlotPlan') && fileIncludes(appJsPath, 'scheduleAppointmentFromCoverage') && fileIncludes(path.join(root, 'assets/core.mjs'), 'slotTemplates'), 'Slot template library, booking conflict queue, and one-click slot-plan repair controls are wired');
check('appointment-outcome-sync', 'appointment outcome sync back into AE command exists', fileIncludes(appJsPath, 'syncAppointmentOutcomeToClient') && fileIncludes(appJsPath, 'appointment-outcome-sync') && fileIncludes(appJsPath, 'renderAppointmentCoverageCard') && fileIncludes(path.join(root, 'assets/core.mjs'), 'syncLog'), 'Appointment outcomes update client state, task follow-through, and sync log state inside AE command');
check('donor-bridge-ops-deck', 'donor bridge ops deck and coverage export exist', fileIncludes(appointmentAdminHtmlPath, 'AE bridge ops deck') && fileIncludes(appointmentAdminJsPath, 'refreshAeBridgeOpsDeck') && fileIncludes(appointmentAdminJsPath, 'exportAeBridgeOpsDeck') && fileIncludes(appointmentServerPath, '/api/admin/ae-bridge/deck'), 'Donor admin bridge ops deck, coverage export, and server endpoint are wired');


check('appointment-revenue-deposit-lane', 'appointment revenue and deposit lane exists', fileIncludes(appJsPath, 'requestAppointmentDeposit') && fileIncludes(appJsPath, 'setAppointmentDepositStatus') && fileIncludes(appJsPath, 'renderAppointmentRevenueCard') && fileIncludes(appJsPath, 'ae-appointment-revenue-brief.md') && fileIncludes(path.join(root, 'assets/core.mjs'), 'depositLedger'), 'Deposit controls, revenue brief export, and deposit state lane are wired');
check('appointment-calendar-capacity-lane', 'appointment calendar capacity lane exists', fileIncludes(appJsPath, 'buildAppointmentCalendarDeck') && fileIncludes(appJsPath, 'renderAppointmentCalendarCard') && fileIncludes(appJsPath, 'ae-appointment-calendar-brief.md') && fileIncludes(appJsPath, 'run-appointment-noshow-rescue'), '7-day slot pressure, calendar brief export, and rescue controls are wired');
check('appointment-rescue-pack-lane', 'appointment rescue pack automation exists', fileIncludes(appJsPath, 'runAppointmentRescuePack') && fileIncludes(appJsPath, 'rescueRuns') && fileIncludes(path.join(root, 'assets/core.mjs'), 'rescueRuns'), 'Watch/no-show rescue automation and rescue history state are wired');
check('donor-revenue-calendar-ops', 'donor admin revenue and calendar ops deck exists', fileIncludes(appointmentAdminHtmlPath, 'AE bridge revenue') && fileIncludes(appointmentAdminJsPath, 'refreshAeBridgeRevenueDeck') && fileIncludes(appointmentAdminJsPath, 'refreshAeBridgeCalendarDeck') && fileIncludes(appointmentServerPath, '/api/admin/ae-bridge/revenue') && fileIncludes(appointmentServerPath, '/api/admin/ae-bridge/calendar'), 'Donor admin revenue/calendar panels and server endpoints are wired');

check('appointment-settlement-lane', 'appointment settlement lane exists', fileIncludes(appJsPath, 'buildAppointmentSettlementDeck') && fileIncludes(appJsPath, 'setAppointmentSettlementStatus') && fileIncludes(appJsPath, 'ae-appointment-settlement-brief.md') && fileIncludes(path.join(root, 'assets/core.mjs'), 'settlementLedger'), 'Settlement rows, invoice status controls, settlement export, and state lane are wired');
check('appointment-funnel-analytics', 'appointment funnel analytics lane exists', fileIncludes(appJsPath, 'buildAppointmentFunnelDeck') && fileIncludes(appJsPath, 'renderAppointmentFunnelCard') && fileIncludes(appJsPath, 'ae-appointment-funnel-brief.md'), 'Handoff-to-revenue funnel analytics card and export lane are wired');
check('appointment-close-pack-automation', 'appointment close-pack automation exists', fileIncludes(appJsPath, 'createAppointmentClosePackTask') && fileIncludes(appJsPath, 'appointment-close-pack') && fileIncludes(appJsPath, 'Closed won — hand off to delivery and archive appointment revenue.'), 'Paid settlement updates client state and creates close-pack follow-through tasking');
check('donor-settlement-funnel-ops', 'donor admin settlement and funnel ops deck exists', fileIncludes(appointmentAdminHtmlPath, 'AE bridge settlements') && fileIncludes(appointmentAdminJsPath, 'refreshAeBridgeSettlementDeck') && fileIncludes(appointmentAdminJsPath, 'refreshAeBridgeFunnelDeck') && fileIncludes(appointmentServerPath, '/api/admin/ae-bridge/settlements') && fileIncludes(appointmentServerPath, '/api/admin/ae-bridge/funnel'), 'Donor admin settlement/funnel panels and server endpoints are wired');


check('appointment-sync-journal', 'appointment bridge sync journal exists', fileIncludes(appJsPath, 'pushAppointmentSyncPacket') && fileIncludes(appJsPath, 'renderAppointmentSyncCard') && fileIncludes(appJsPath, 'ae-appointment-sync-brief.md') && fileIncludes(path.join(root, 'assets/core.mjs'), 'syncJournal'), 'Sync packet logger, retry/resolve controls, export lane, and sync journal state are wired');
check('appointment-fulfillment-board', 'appointment fulfillment board exists', fileIncludes(appJsPath, 'createAppointmentFulfillmentPacket') && fileIncludes(appJsPath, 'renderAppointmentFulfillmentCard') && fileIncludes(appJsPath, 'ae-appointment-fulfillment-brief.md') && fileIncludes(path.join(root, 'assets/core.mjs'), 'fulfillmentPackets'), 'Fulfillment packet board, status controls, export lane, and fulfillment state are wired');
check('omega-brief-sync-fulfillment', '0mega brief includes sync and fulfillment visibility', fileIncludes(appJsPath, 'appointmentSync: buildAppointmentSyncDeck()') && fileIncludes(appJsPath, 'appointmentFulfillment: buildAppointmentFulfillmentDeck()') && fileIncludes(appJsPath, 'Sync packets queued') && fileIncludes(appJsPath, 'Fulfillment packets active'), 'Combined 0mega brief carries sync pressure and fulfillment packet visibility');
check('donor-sync-fulfillment-ops', 'donor admin sync and fulfillment ops deck exists', fileIncludes(appointmentAdminHtmlPath, 'AE bridge sync') && fileIncludes(appointmentAdminHtmlPath, 'AE bridge fulfillment') && fileIncludes(appointmentAdminJsPath, 'refreshAeBridgeSyncDeck') && fileIncludes(appointmentAdminJsPath, 'refreshAeBridgeFulfillmentDeck') && fileIncludes(appointmentServerPath, '/api/admin/ae-bridge/sync') && fileIncludes(appointmentServerPath, '/api/admin/ae-bridge/fulfillment'), 'Donor admin sync/fulfillment panels and server endpoints are wired');

check('appointment-orchestration-deck', 'appointment orchestration deck exists', fileIncludes(appJsPath, 'buildAppointmentOrchestrationDeck') && fileIncludes(appJsPath, 'renderAppointmentOrchestrationCard') && fileIncludes(appJsPath, 'ae-appointment-orchestration-brief.md') && fileIncludes(appJsPath, 'appointment-sync-retry-all'), 'Orchestration deck, retry-all/resolve-ready controls, and export lane are wired');
check('appointment-profitability-deck', 'appointment profitability deck exists', fileIncludes(appJsPath, 'buildAppointmentProfitabilityDeck') && fileIncludes(appJsPath, 'renderAppointmentProfitabilityCard') && fileIncludes(appJsPath, 'ae-appointment-profitability-brief.md') && fileIncludes(appJsPath, 'Net appointment position'), 'Profitability deck, margin-watch visibility, and export lane are wired');
check('appointment-fulfillment-templates', 'appointment fulfillment templates exist', fileIncludes(appJsPath, 'APPOINTMENT_FULFILLMENT_TEMPLATE_LIBRARY') && fileIncludes(appJsPath, 'applyAppointmentFulfillmentTemplate') && fileIncludes(appJsPath, 'appointment-fulfillment-template-premium') && fileIncludes(path.join(root, 'assets/core.mjs'), 'fulfillmentTemplates'), 'Fulfillment template library, checklist generation, and linked task creation are wired');
check('donor-profitability-template-ops', 'donor admin profitability and template ops deck exists', fileIncludes(appointmentAdminHtmlPath, 'AE bridge profitability') && fileIncludes(appointmentAdminHtmlPath, 'AE bridge templates') && fileIncludes(appointmentAdminJsPath, 'refreshAeBridgeProfitabilityDeck') && fileIncludes(appointmentAdminJsPath, 'refreshAeBridgeTemplateDeck') && fileIncludes(appointmentServerPath, '/api/admin/ae-bridge/profitability') && fileIncludes(appointmentServerPath, '/api/admin/ae-bridge/templates'), 'Donor admin profitability/template panels and server endpoints are wired');


check('printful-catalog-control', 'printful catalog control exists', fileIncludes(appJsPath, 'buildPrintfulCatalogDeck') && fileIncludes(appJsPath, 'renderPrintfulCatalogDeck') && fileIncludes(appJsPath, 'ae-printful-catalog.md') && fileIncludes(appJsPath, 'product-family pressure') === false ? fileIncludes(appJsPath, 'Product-family pressure') || fileIncludes(appJsPath, 'familyPressure') : true, 'Catalog deck, demand routing, and catalog export lane are wired');
check('printful-order-control', 'printful order control exists', fileIncludes(appJsPath, 'requestPrintfulQuoteApproval') && fileIncludes(appJsPath, 'markPrintfulDepositPaid') && fileIncludes(appJsPath, 'markPrintfulBalancePaid') && fileIncludes(appJsPath, 'returnPrintfulOrderToAe') && fileIncludes(appJsPath, 'printful-promote-production'), 'Quote/deposit/balance/promotion/return controls are wired');
check('printful-art-packet-board', 'printful art packet board exists', fileIncludes(appJsPath, 'ensurePrintfulArtPacket') && fileIncludes(appJsPath, 'renderPrintfulArtPacketCard') && fileIncludes(appJsPath, 'ae-printful-art-packets') && fileIncludes(appJsPath, 'printful-art-revise'), 'Art packet board, proof-send, approval, and revision controls are wired');
check('printful-ops-automation', 'printful ops automation exists', fileIncludes(appJsPath, 'buildPrintfulProductionPressureDeck') && fileIncludes(appJsPath, 'runPrintfulRescueSweep') && fileIncludes(appJsPath, 'ae-printful-production') && fileIncludes(appJsPath, 'ae-printful-founder-packet'), 'Production pressure deck, rescue sweep, and founder export packets are wired');
check('printful-profitability-lane', 'printful profitability lane exists', fileIncludes(appJsPath, 'buildPrintfulProfitabilityDeck') && fileIncludes(appJsPath, 'renderPrintfulProfitabilityCard') && fileIncludes(appJsPath, 'ae-printful-performance') && fileIncludes(appJsPath, 'netPosition'), 'Profitability deck, collected/reserve/net visibility, and export lane are wired');
check('printful-shared-contract-lane', 'printful shared contract lane exists', fileIncludes(appJsPath, 'normalizePrintfulSharedContract') && fileIncludes(appJsPath, 'pushPrintfulContractPacket') && fileIncludes(appJsPath, 'queuePrintfulReplay') && fileIncludes(appJsPath, 'ae-printful-contract'), 'Shared contract normalization, contract packets, replay queue, and contract export lane are wired');
check('printful-presence-proof-lane', 'printful multi-user presence proof lane exists', fileIncludes(appJsPath, 'buildPrintfulPresenceDeck') && fileIncludes(appJsPath, 'renderPrintfulPresenceCard') && fileIncludes(appJsPath, 'printful-claim-lock') && fileIncludes(appJsPath, 'ae-printful-presence'), 'Operator session proof, order lock controls, and presence export lane are wired');
check('printful-hardening-audit-lane', 'printful deployment hardening lane exists', fileIncludes(appJsPath, 'runPrintfulDeploymentHardeningAudit') && fileIncludes(appJsPath, 'renderPrintfulHardeningCard') && fileIncludes(appJsPath, 'printful-run-hardening-audit') && fileIncludes(appJsPath, 'ae-printful-hardening'), 'Deployment hardening audit, readiness deck, and export lane are wired');
check('printful-donor-presence-hardening', 'printful donor presence and hardening decks exist', fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/site/printful-pod/partials/admin-shell.html'), 'AE bridge presence') && fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/site/printful-pod/partials/admin-shell.html'), 'AE bridge deployment hardening') && fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/site/printful-pod/assets/js/printful-admin.js'), 'refreshAeBridgePresenceDeck') && fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/site/printful-pod/assets/js/printful-admin.js'), 'refreshAeBridgeHardeningDeck') && fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/netlify/functions/printful-ae-bridge-presence.js'), 'aeBridgePresence') && fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/netlify/functions/printful-ae-bridge-hardening.js'), 'aeBridgeHardening'), 'Donor admin presence/hardening decks and export endpoints are wired');
check('printful-donor-contract-profit-art', 'printful donor contract/art/profitability decks exist', fileIncludes(launcherAppJsPath, 'omega-printful-upgrade') && fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/site/printful-pod/partials/admin-shell.html'), 'AE bridge contract') && fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/site/printful-pod/partials/admin-shell.html'), 'AE bridge art packets') && fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/site/printful-pod/partials/admin-shell.html'), 'AE bridge profitability') && fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/site/printful-pod/assets/js/printful-admin.js'), 'refreshAeBridgeContractDeck') && fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/site/printful-pod/assets/js/printful-admin.js'), 'refreshAeBridgeProfitabilityDeck'), 'Donor admin contract, art packet, and profitability decks are wired');
check('printful-returns-remediation-lane', 'printful returns and remediation lane exists', fileIncludes(appJsPath, 'buildPrintfulReturnsDeck') && fileIncludes(appJsPath, 'requestPrintfulReturn') && fileIncludes(appJsPath, 'ae-printful-returns') && fileIncludes(appJsPath, 'printful-return-request'), 'Return tickets, refund/reprint controls, and returns export lane are wired');
check('printful-incident-sla-lane', 'printful incident and SLA lane exists', fileIncludes(appJsPath, 'buildPrintfulIncidentDeck') && fileIncludes(appJsPath, 'runPrintfulIncidentSweep') && fileIncludes(appJsPath, 'ae-printful-incidents') && fileIncludes(appJsPath, 'printful-incident-task'), 'Incident sweep, SLA pressure deck, rescue-task controls, and incident export lane are wired');
check('printful-donor-returns-incidents', 'printful donor returns and incidents decks exist', fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/site/printful-pod/partials/admin-shell.html'), 'AE bridge returns') && fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/site/printful-pod/partials/admin-shell.html'), 'AE bridge incidents') && fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/site/printful-pod/assets/js/printful-admin.js'), 'refreshAeBridgeReturnsDeck') && fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/site/printful-pod/assets/js/printful-admin.js'), 'refreshAeBridgeIncidentDeck') && fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/netlify/functions/printful-ae-bridge-returns.js'), 'AE bridge returns export failed') && fileIncludes(path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/netlify/functions/printful-ae-bridge-incidents.js'), 'AE bridge incidents export failed'), 'Donor admin returns/incidents decks and export endpoints are wired');

check('assignment-confidence-lane', 'assignment confidence lane exists', fileIncludes(appJsPath, 'function getAssignmentConfidence(client)') && fileIncludes(appJsPath, 'getAssignmentReviewQueue(limit = 8)') && fileIncludes(appJsPath, 'confidence-prep-export') && fileIncludes(appJsPath, 'High confidence'), 'Assignment confidence scoring, review queue, and prep export controls are wired');
check('client-escalation-control-lane', 'client escalation control lane exists', fileIncludes(appJsPath, 'function getClientEscalationState(client)') && fileIncludes(appJsPath, "function setClientEscalation(clientId, level = 'watch'") && fileIncludes(appJsPath, 'client-escalation-level') && fileIncludes(appJsPath, 'client-escalation-task') && fileIncludes(appJsPath, 'exportEscalationBrief'), 'Escalation fields, queue, control actions, and escalation export lane are wired');
check('escalation-rescue-task-lane', 'escalation rescue task automation exists', fileIncludes(appJsPath, "function createEscalationRescueTask(clientId, source = 'escalation-rescue'") && fileIncludes(appJsPath, 'Escalation rescue — ${client.name}') && fileIncludes(appJsPath, 'escalation-create-task'), 'Escalation rescue task creation and dashboard controls are wired');
check('ae-prep-brief-lane', 'AE prep brief export lane exists', fileIncludes(appJsPath, 'function buildAePrepBrief(clientId)') && fileIncludes(appJsPath, "function exportAePrepBrief(clientId, format = 'json'") && fileIncludes(appJsPath, 'AE prep brief preview') && fileIncludes(appJsPath, 'ae-prep-brief.md'), 'AE prep brief builder, preview, and JSON/Markdown export are wired');
check('smoke-path-hardening', 'smoke and directive path hardening exist', fileIncludes(path.join(root, 'scripts/smoke.mjs'), 'function resolvePackRoot()') && fileIncludes(path.join(root, 'scripts/update-directive.mjs'), 'function resolvePackRoot()'), 'Smoke and directive scripts can resolve pack root from launcher or branch cwd');

const renewalRiskRuntime = core.getClientRenewalRiskState({ name: 'Retention Test', stage: 'active', priority: 'urgent', monthlyValue: 5400, estimatedValue: 24000, closeProbability: 42, followUpDate: '2026-04-03', targetCloseDate: '2026-04-07', escalationLevel: 'executive', notes: 'renew immediately' }, '2026-04-05');
check('renewal-risk-runtime', 'renewal risk runtime exists', renewalRiskRuntime.status === 'critical' && Number(renewalRiskRuntime.atRiskValue || 0) >= 15000, `Renewal runtime status ${renewalRiskRuntime.status} with at-risk ${renewalRiskRuntime.atRiskValue}`);

const coveragePressureRuntime = core.getAeCoveragePressureState({ id: 'AE-TEST', enabled: true, availabilityState: 'focus', dailyCap: 10, usageToday: 10, monthlyCap: 120, usageMonth: 110, assignments: 19, unavailableUntil: '2026-04-06' });
check('coverage-pressure-runtime', 'coverage pressure runtime exists', coveragePressureRuntime.status === 'critical' && coveragePressureRuntime.score >= 75, `Coverage runtime status ${coveragePressureRuntime.status} with score ${coveragePressureRuntime.score}`);

const normalizedCommandState = core.normalizeState({ renewalRuns: [{ id: 'renewal-run-test' }], coverageRuns: [{ id: 'coverage-run-test' }] }, roster);
check('renewal-coverage-run-history', 'renewal and coverage run ledgers exist', Array.isArray(normalizedCommandState.renewalRuns) && normalizedCommandState.renewalRuns.length === 1 && Array.isArray(normalizedCommandState.coverageRuns) && normalizedCommandState.coverageRuns.length === 1 && fileIncludes(path.join(root, 'assets/core.mjs'), 'renewalRuns') && fileIncludes(path.join(root, 'assets/core.mjs'), 'coverageRuns'), 'State normalization preserves renewalRuns and coverageRuns ledgers');

check('renewal-command-center-lane', 'renewal command center lane exists', fileIncludes(appJsPath, 'function buildRenewalCommandDeck()') && fileIncludes(appJsPath, 'renderRenewalCommandCard') && fileIncludes(appJsPath, 'Renewal command center') && fileIncludes(appJsPath, 'ae-renewal-command-brief.md'), 'Renewal risk deck, dashboard rendering, and JSON/Markdown export lane are wired');
check('renewal-save-brief-lane', 'renewal save brief and rescue task lane exist', fileIncludes(appJsPath, 'function buildRenewalSaveBrief(clientId)') && fileIncludes(appJsPath, "function exportRenewalSaveBrief(clientId, format = 'json')") && fileIncludes(appJsPath, "function createRenewalRescueTask(clientId, source = 'renewal-rescue')") && fileIncludes(appJsPath, 'Renewal save brief preview') && fileIncludes(appJsPath, 'ae-renewal-save-brief.md'), 'Renewal save brief preview, export lane, and rescue-task automation are wired');
check('ae-coverage-pressure-command', 'AE coverage pressure command lane exists', fileIncludes(appJsPath, 'function buildAeCoveragePressureDeck()') && fileIncludes(appJsPath, 'renderCoveragePressureCard') && fileIncludes(appJsPath, 'AE coverage pressure') && fileIncludes(appJsPath, 'ae-coverage-pressure-brief.md'), 'Coverage pressure deck, dashboard rendering, and JSON/Markdown export lane are wired');
check('coverage-relief-sweep-lane', 'coverage relief sweep lane exists', fileIncludes(appJsPath, 'function runCoverageReliefSweep(limit = 5)') && fileIncludes(appJsPath, 'coverage-relief-sweep') && fileIncludes(appJsPath, 'Run relief sweep') && fileIncludes(appJsPath, 'Coverage relief — ${ae.name}'), 'Coverage relief sweep, reassignment lane, and relief task creation are wired');

const reactivationRuntime = core.getClientReactivationState({ name: 'Cold Client', stage: 'active', priority: 'high', monthlyValue: 6200, estimatedValue: 18000, closeProbability: 45, followUpDate: '2026-04-01', lastContactAt: '2026-03-07', notes: 'ghosted and stale; reactivate immediately' }, '2026-04-05');
check('reactivation-runtime', 'reactivation runtime exists', reactivationRuntime.status === 'critical' && Number(reactivationRuntime.recoverableValue || 0) >= 12000, `Reactivation runtime status ${reactivationRuntime.status} with recoverable ${reactivationRuntime.recoverableValue}`);

const normalizedContinuityState = core.normalizeState({ reactivationRuns: [{ id: 'reactivation-run-test' }], handoffRuns: [{ id: 'handoff-run-test' }] }, roster);
check('command-recovery-sweep-ledgers', 'reactivation and handoff run ledgers exist', Array.isArray(normalizedContinuityState.reactivationRuns) && normalizedContinuityState.reactivationRuns.length === 1 && Array.isArray(normalizedContinuityState.handoffRuns) && normalizedContinuityState.handoffRuns.length === 1 && fileIncludes(path.join(root, 'assets/core.mjs'), 'reactivationRuns') && fileIncludes(path.join(root, 'assets/core.mjs'), 'handoffRuns'), 'State normalization preserves reactivationRuns and handoffRuns ledgers');
check('reactivation-command-deck', 'reactivation command deck exists', fileIncludes(appJsPath, 'function buildReactivationCommandDeck()') && fileIncludes(appJsPath, 'renderReactivationCommandCard') && fileIncludes(appJsPath, 'Reactivation command') && fileIncludes(appJsPath, 'ae-reactivation-command-brief.md'), 'Dormant revenue deck, dashboard rendering, and JSON/Markdown export lane are wired');
check('reactivation-brief-task-lane', 'reactivation brief and task automation exist', fileIncludes(appJsPath, 'function buildReactivationBrief(clientId)') && fileIncludes(appJsPath, "function exportReactivationBrief(clientId, format = 'json')") && fileIncludes(appJsPath, "function createReactivationTask(clientId, source = 'reactivation-recovery')") && fileIncludes(appJsPath, 'Reactivation brief preview') && fileIncludes(appJsPath, 'ae-reactivation-brief.md'), 'Reactivation brief preview, export lane, and rescue-task automation are wired');
check('handoff-continuity-deck', 'handoff continuity deck exists', fileIncludes(appJsPath, 'function buildHandoffCommandDeck()') && fileIncludes(appJsPath, 'renderHandoffCommandCard') && fileIncludes(appJsPath, 'Handoff continuity') && fileIncludes(appJsPath, 'ae-handoff-command-brief.md'), 'Handoff continuity deck, continuity scoring, and JSON/Markdown export lane are wired');
check('client-handoff-packet-lane', 'client handoff packet and follow-through lane exist', fileIncludes(appJsPath, 'function buildClientHandoffPacket(clientId)') && fileIncludes(appJsPath, "function exportClientHandoffPacket(clientId, format = 'json')") && fileIncludes(appJsPath, "function createHandoffFollowThroughTask(clientId, source = 'handoff-follow-through')") && fileIncludes(appJsPath, 'Client handoff packet preview') && fileIncludes(appJsPath, 'ae-client-handoff-packet.md'), 'Client transfer packet, preview, and follow-through task automation are wired');
check('command-recovery-sweep-exists', 'command recovery sweep exists', fileIncludes(appJsPath, 'function runCommandRecoverySweep(limit = 6)') && fileIncludes(appJsPath, 'run-command-recovery-sweep') && fileIncludes(appJsPath, 'command-recovery-sweep'), 'Command recovery sweep orchestrates escalation, renewal, reactivation, coverage, and handoff rescue actions');

const promiseRuntime = core.getClientPromiseIntegrityState({ id: 'promise-client', name: 'Promise Client', stage: 'active', priority: 'urgent', monthlyValue: 5400, estimatedValue: 18000, followUpDate: '2026-04-01', targetCloseDate: '2026-04-03', nextStep: '', notes: 'Client is angry about missed SLA and late promise' }, [{ clientId: 'promise-client', status: 'todo', dueDate: '2026-04-02' }, { clientId: 'promise-client', status: 'todo', dueDate: '2026-04-03' }], [{ clientId: 'promise-client', state: 'open', updatedAt: '2026-03-20' }], '2026-04-05');
check('promise-integrity-runtime', 'promise integrity runtime exists', promiseRuntime.status === 'critical' && Number(promiseRuntime.exposedValue || 0) >= 10000 && Number(promiseRuntime.overdueTaskCount || 0) >= 2, `Promise runtime status ${promiseRuntime.status} with exposed ${promiseRuntime.exposedValue}`);
const promiseLoadRuntime = core.buildAePromiseLoadSummary([{ id: 'ae-1', name: 'Avery' }, { id: 'ae-2', name: 'Jordan' }], [{ id: 'client-1', assignedAeId: 'ae-1', monthlyValue: 5400, estimatedValue: 18000, stage: 'active', priority: 'urgent', followUpDate: '2026-04-01', notes: 'missed sla', nextStep: '' }], [{ assignedAeId: 'ae-1', clientId: 'client-1', status: 'todo', dueDate: '2026-04-02' }], [{ clientId: 'client-1', updatedAt: '2026-03-20' }], '2026-04-05');
check('ae-promise-load-runtime', 'AE promise load runtime exists', Array.isArray(promiseLoadRuntime.rows) && promiseLoadRuntime.rows.length === 2 && ['critical', 'high', 'watch', 'healthy'].includes(promiseLoadRuntime.rows[0].status), `Promise load rows: ${promiseLoadRuntime.rows.length}`);
const normalizedPromiseState = core.normalizeState({ promiseRuns: [{ id: 'promise-run-test' }], serviceRecoveryRuns: [{ id: 'service-recovery-run-test' }] }, roster);
check('promise-ledger-persistence', 'promise and service-recovery ledgers exist', Array.isArray(normalizedPromiseState.promiseRuns) && normalizedPromiseState.promiseRuns.length === 1 && Array.isArray(normalizedPromiseState.serviceRecoveryRuns) && normalizedPromiseState.serviceRecoveryRuns.length === 1 && fileIncludes(path.join(root, 'assets/core.mjs'), 'promiseRuns') && fileIncludes(path.join(root, 'assets/core.mjs'), 'serviceRecoveryRuns'), 'State normalization preserves promiseRuns and serviceRecoveryRuns ledgers');
check('promise-integrity-command', 'promise integrity command deck exists', fileIncludes(appJsPath, 'function buildPromiseIntegrityCommandDeck()') && fileIncludes(appJsPath, 'renderPromiseIntegrityCommandCard') && fileIncludes(appJsPath, 'Promise integrity') && fileIncludes(appJsPath, 'ae-promise-integrity-brief.md'), 'Promise-integrity deck, dashboard rendering, and JSON/Markdown export lane are wired');
check('service-recovery-brief-lane', 'service recovery brief lane exists', fileIncludes(appJsPath, 'function buildServiceRecoveryBrief(clientId)') && fileIncludes(appJsPath, "function exportServiceRecoveryBrief(clientId, format = 'json')") && fileIncludes(appJsPath, 'Service recovery brief preview') && fileIncludes(appJsPath, 'ae-service-recovery-brief.md'), 'Service recovery brief preview, opener, compensation levers, and JSON/Markdown export are wired');
check('service-recovery-task-lane', 'service recovery task lane exists', fileIncludes(appJsPath, "function createServiceRecoveryTask(clientId, source = 'service-recovery')") && fileIncludes(appJsPath, 'Service recovery — ${client.name}') && fileIncludes(appJsPath, 'service-recovery') && fileIncludes(appJsPath, 'promise-recovery-sweep'), 'Service recovery task automation and promise recovery sweep are wired');
check('ae-promise-load-deck', 'AE promise load deck exists', fileIncludes(appJsPath, 'function buildAePromiseLoadDeck()') && fileIncludes(appJsPath, 'renderAePromiseLoadCard') && fileIncludes(appJsPath, 'AE promise load') && fileIncludes(appJsPath, 'ae-promise-load-brief.md'), 'AE promise-load deck, dashboard rendering, and JSON/Markdown export lane are wired');
check('promise-recovery-sweep-exists', 'promise recovery sweep exists', fileIncludes(appJsPath, 'function runPromiseRecoverySweep(limit = 5)') && fileIncludes(appJsPath, 'run-promise-recovery-sweep') && fileIncludes(appJsPath, 'promise-recovery-sweep'), 'Promise recovery sweep orchestrates service-recovery task creation for breach-risk clients');

const churnRuntime = core.getClientChurnRiskState({ id: 'churn-client', name: 'Churn Client', stage: 'active', priority: 'urgent', monthlyValue: 6200, estimatedValue: 24000, closeProbability: 38, followUpDate: '2026-04-01', targetCloseDate: '2026-04-03', lastContactAt: '2026-03-20', notes: 'client may cancel and go to competitor; frustrated and disappointed' }, [{ clientId: 'churn-client', status: 'todo', dueDate: '2026-04-02' }, { clientId: 'churn-client', status: 'todo', dueDate: '2026-04-03' }], [{ clientId: 'churn-client', state: 'open', updatedAt: '2026-03-21' }], '2026-04-05');
check('churn-risk-runtime', 'churn risk runtime exists', churnRuntime.status === 'critical' && Number(churnRuntime.exposedValue || 0) >= 15000, `Churn runtime status ${churnRuntime.status} with exposed ${churnRuntime.exposedValue}`);
const aeChurnRuntime = core.buildAeChurnExposureSummary([{ id: 'ae-1', name: 'Avery' }, { id: 'ae-2', name: 'Jordan' }], [{ id: 'client-1', assignedAeId: 'ae-1', monthlyValue: 6200, estimatedValue: 18000, stage: 'active', priority: 'urgent', followUpDate: '2026-04-01', lastContactAt: '2026-03-20', notes: 'might cancel and go competitor', nextStep: '' }], [{ assignedAeId: 'ae-1', clientId: 'client-1', status: 'todo', dueDate: '2026-04-02' }], [{ clientId: 'client-1', aeId: 'ae-1', updatedAt: '2026-03-21' }], '2026-04-05');
check('ae-churn-exposure-runtime', 'AE churn exposure runtime exists', Array.isArray(aeChurnRuntime.rows) && aeChurnRuntime.rows.length === 2 && ['critical', 'high', 'watch', 'healthy'].includes(aeChurnRuntime.rows[0].status), `AE churn rows: ${aeChurnRuntime.rows.length}`);
const normalizedChurnState = core.normalizeState({ churnRuns: [{ id: 'churn-run-test' }], savePlanRuns: [{ id: 'save-plan-run-test' }] }, roster);
check('churn-ledger-persistence', 'churn and save-plan ledgers exist', Array.isArray(normalizedChurnState.churnRuns) && normalizedChurnState.churnRuns.length === 1 && Array.isArray(normalizedChurnState.savePlanRuns) && normalizedChurnState.savePlanRuns.length === 1 && fileIncludes(path.join(root, 'assets/core.mjs'), 'churnRuns') && fileIncludes(path.join(root, 'assets/core.mjs'), 'savePlanRuns'), 'State normalization preserves churnRuns and savePlanRuns ledgers');
check('churn-defense-command', 'churn defense command deck exists', fileIncludes(appJsPath, 'function buildChurnDefenseCommandDeck()') && fileIncludes(appJsPath, 'renderChurnDefenseCommandCard') && fileIncludes(appJsPath, 'Churn defense') && fileIncludes(appJsPath, 'ae-churn-defense-brief.md'), 'Churn-defense deck, dashboard rendering, and JSON/Markdown export lane are wired');
check('executive-save-plan-lane', 'executive save plan lane exists', fileIncludes(appJsPath, 'function buildExecutiveSavePlan(clientId)') && fileIncludes(appJsPath, "function exportExecutiveSavePlan(clientId, format = 'json')") && fileIncludes(appJsPath, 'Executive save plan preview') && fileIncludes(appJsPath, 'ae-executive-save-plan.md'), 'Executive save plan preview, opener, retention levers, and JSON/Markdown export are wired');
check('churn-defense-task-lane', 'churn defense task lane exists', fileIncludes(appJsPath, "function createChurnDefenseTask(clientId, source = 'churn-defense')") && fileIncludes(appJsPath, 'Churn defense — ${client.name}') && fileIncludes(appJsPath, 'churn-defense-sweep') && fileIncludes(appJsPath, 'run-churn-defense-sweep'), 'Churn defense task automation and churn defense sweep are wired');
check('ae-churn-exposure-deck', 'AE churn exposure deck exists', fileIncludes(appJsPath, 'function buildAeChurnExposureDeck()') && fileIncludes(appJsPath, 'renderAeChurnExposureCard') && fileIncludes(appJsPath, 'AE churn exposure') && fileIncludes(appJsPath, 'ae-churn-exposure-brief.md'), 'AE churn-exposure deck, dashboard rendering, and JSON/Markdown export lane are wired');

check('offer-fit-runtime', 'offer fit runtime exists', (() => {
  const offerFitRuntime = core.getClientOfferFitState({ id: 'offer-client', name: 'Offer Client', company: 'Growth Commerce Group', stage: 'new', priority: 'urgent', clientType: 'executive,technical', tags: 'zip, valuation, sales, ecommerce', notes: 'needs deep scan, website valuation, and merch commerce expansion', nextStep: 'review command pack and printful lane', monthlyValue: 6200, estimatedValue: 28000, followUpDate: '2026-04-06' }, core.DEFAULT_OFFER_CATALOG);
  return offerFitRuntime.status === 'hot' && Number(offerFitRuntime.totalProjectedValue || 0) >= 60000 && Array.isArray(offerFitRuntime.topOffers) && offerFitRuntime.topOffers.length >= 2;
})(), 'Offer-fit runtime surfaces hot opportunities with top-offer recommendations');
const offerCoverageRuntime = core.buildAeOfferCoverageSummary([{ id: 'ae-1', name: 'Avery' }, { id: 'ae-2', name: 'Jordan' }], [{ id: 'client-1', assignedAeId: 'ae-1', stage: 'new', priority: 'urgent', clientType: 'executive,technical', tags: 'zip, valuation, sales', notes: 'needs scan and command platform', estimatedValue: 24000, monthlyValue: 6200 }], core.DEFAULT_OFFER_CATALOG);
check('ae-offer-coverage-runtime', 'AE offer coverage runtime exists', Array.isArray(offerCoverageRuntime.rows) && offerCoverageRuntime.rows.length === 2 && ['critical', 'high', 'watch', 'healthy'].includes(offerCoverageRuntime.rows[0].status), `AE offer coverage rows: ${offerCoverageRuntime.rows.length}`);
const normalizedOfferState = core.normalizeState({ offerRuns: [{ id: 'offer-run-test' }], offerPacketRuns: [{ id: 'offer-packet-run-test' }] }, roster);
check('offer-ledger-persistence', 'offer and offer-packet ledgers exist', Array.isArray(normalizedOfferState.offerRuns) && normalizedOfferState.offerRuns.length === 1 && Array.isArray(normalizedOfferState.offerPacketRuns) && normalizedOfferState.offerPacketRuns.length === 1 && fileIncludes(path.join(root, 'assets/core.mjs'), 'offerRuns') && fileIncludes(path.join(root, 'assets/core.mjs'), 'offerPacketRuns'), 'State normalization preserves offerRuns and offerPacketRuns ledgers');
check('offer-command-deck', 'offer command deck exists', fileIncludes(appJsPath, 'function buildOfferCommandDeck()') && fileIncludes(appJsPath, 'renderOfferCommandCard') && fileIncludes(appJsPath, 'Product offer command') && fileIncludes(appJsPath, 'ae-offer-command-brief.md'), 'Offer-command deck, dashboard rendering, and JSON/Markdown export lane are wired');
check('client-offer-packet-lane', 'client offer packet lane exists', fileIncludes(appJsPath, 'function buildClientOfferPacket(clientId)') && fileIncludes(appJsPath, "function exportClientOfferPacket(clientId, format = 'json')") && fileIncludes(appJsPath, 'AE Client Offer Packet') && fileIncludes(appJsPath, 'ae-client-offer-packet.md'), 'Client offer packet preview, bundle logic, and JSON/Markdown export are wired');
check('offer-command-task-lane', 'offer command task lane exists', fileIncludes(appJsPath, "function createOfferPursuitTask(clientId, source = 'offer-command')") && fileIncludes(appJsPath, 'Offer pursuit — ${client.name}') && fileIncludes(appJsPath, 'offer-command-sweep') && fileIncludes(appJsPath, 'run-offer-command-sweep'), 'Offer pursuit task automation and offer-command sweep are wired');
check('indexed-storage-hybrid-lane', 'indexed storage hybrid lane exists', fileIncludes(appJsPath, 'loadHybridState') && fileIncludes(appJsPath, 'saveHybridState') && fileIncludes(appJsPath, 'syncHybridStateToNeon') && fs.existsSync(path.join(root, 'assets/storage.mjs')), 'AE branch app now includes localStorage preservation, IndexedDB storage, and Neon sync hooks.');
check('neon-storage-sync-lane', 'neon storage sync lane exists', fs.existsSync(path.join(netlifyRoot, 'ae-storage-sync.js')) && fileIncludes(path.join(netlifyRoot, 'ae-storage-sync.js'), 'IndexedDB hybrid snapshot persisted to Neon') && fileIncludes(path.join(packRoot, 'db/ae_brain_command_site.sql'), 'ae_branch_state_versions') && fileIncludes(path.join(packRoot, 'db/ae_brain_command_site.sql'), 'ae_branch_storage_sync_events'), 'Neon-backed storage sync endpoint and SQL ledger tables are wired.');
check('media-center-app-lane', 'media center app exists', fs.existsSync(path.join(packRoot, 'Branching Apps/Skye-Media-Center-v1/index.html')) && fs.existsSync(path.join(packRoot, 'Branching Apps/Skye-Media-Center-v1/artist.html')) && fileIncludes(path.join(packRoot, 'Branching Apps/Skye-Media-Center-v1/index.html'), 'Artist pages, music streaming') && fileIncludes(path.join(packRoot, 'assets/app.js'), 'Skye Media Center'), 'Media center studio and artist page are present in the pack and linked from the launcher.');
check('artist-share-page-lane', 'artist share page lane exists', fs.existsSync(path.join(packRoot, 'pages/media-center.html')) && fs.existsSync(path.join(packRoot, 'pages/artist-share.html')) && fileIncludes(path.join(packRoot, 'pages/media-center.html'), 'Spotify + Instagram + YouTube-inspired behavior') && fileIncludes(path.join(packRoot, 'pages/artist-share.html'), 'public artist page'), 'Root-shell guide and public share page are packaged.');
check('media-center-neon-api-lane', 'media center Neon API exists', fs.existsSync(path.join(netlifyRoot, 'media-center.js')) && fileIncludes(path.join(netlifyRoot, 'media-center.js'), 'upsertArtist') && fileIncludes(path.join(netlifyRoot, 'media-center.js'), 'upsertEntry') && fileIncludes(path.join(packRoot, 'db/ae_brain_command_site.sql'), 'media_center_artists') && fileIncludes(path.join(packRoot, 'db/ae_brain_command_site.sql'), 'media_center_entries'), 'Media center metadata API and SQL tables are wired for Neon.');
check('media-center-video-upload-lane', 'media center direct video upload lane exists', fileIncludes(path.join(packRoot, 'Branching Apps/Skye-Media-Center-v1/index.html'), 'Direct Video Upload') && fileIncludes(path.join(packRoot, 'Branching Apps/Skye-Media-Center-v1/assets/app.js'), 'entryVideoFile') && fileIncludes(path.join(netlifyRoot, 'media-center.js'), 'videoDataUrl') && fileIncludes(path.join(netlifyRoot, 'media-center.js'), 'transcodeVideoAsset'), 'Studio UI, direct upload field, and server-side video intake/transcode lane are wired.');
check('media-center-video-stream-lane', 'media center direct video stream lane exists', fileIncludes(path.join(packRoot, 'Branching Apps/Skye-Media-Center-v1/assets/app.js'), '<video class=\"video\" controls') && fileIncludes(path.join(packRoot, 'Branching Apps/Skye-Media-Center-v1/assets/artist.js'), '<video class=\"video\" controls') && fileIncludes(path.join(netlifyRoot, 'media-center.js'), 'assetKey') && fileIncludes(path.join(packRoot, 'db/ae_brain_command_site.sql'), 'media_center_assets') && fileIncludes(path.join(packRoot, 'db/ae_brain_command_site.sql'), 'media_center_video_variants'), 'Public pages, stream endpoint, and SQL-ledgered video asset tables are wired.');
const smokeVideoDir = path.join(packRoot, '.smoke-media');
fs.mkdirSync(smokeVideoDir, { recursive: true });
const smokeVideoSource = path.join(smokeVideoDir, 'smoke-input.mp4');
try { execSync(`ffmpeg -y -f lavfi -i testsrc=size=640x360:rate=24 -f lavfi -i sine=frequency=880:sample_rate=44100 -t 1.2 -c:v libx264 -pix_fmt yuv420p -c:a aac -shortest "${smokeVideoSource}"`, { stdio: 'pipe' }); } catch (error) {}
let mediaTranscodeOk = false;
let mediaTranscodeDetail = 'video transcode smoke did not run';
try {
  const smokeBuffer = fs.readFileSync(smokeVideoSource);
  const smokeDataUrl = `data:video/mp4;base64,${smokeBuffer.toString('base64')}`;
  const transcodeResult = await mediaVideo.transcodeVideoAsset({ artistSlug: 'smoke-artist', title: 'Smoke Clip', dataUrl: smokeDataUrl, mimeType: 'video/mp4', filename: 'smoke-input.mp4' });
  mediaTranscodeOk = Boolean(transcodeResult.poster?.storageKey) && Array.isArray(transcodeResult.variants) && transcodeResult.variants.length >= 1 && transcodeResult.durationSeconds > 0;
  mediaTranscodeDetail = `variants=${transcodeResult.variants.length}, duration=${transcodeResult.durationSeconds}`;
} catch (error) {
  mediaTranscodeDetail = error?.message || 'video transcode smoke failed';
}
check('media-center-video-transcode-runtime', 'media center video transcode runtime exists', mediaTranscodeOk, mediaTranscodeDetail);
check('ae-offer-coverage-deck', 'AE offer coverage deck exists', fileIncludes(appJsPath, 'function buildAeOfferCoverageDeck()') && fileIncludes(appJsPath, 'renderAeOfferCoverageCard') && fileIncludes(appJsPath, 'AE offer coverage') && fileIncludes(appJsPath, 'ae-offer-coverage-brief.md'), 'AE offer-coverage deck, dashboard rendering, and JSON/Markdown export lane are wired');

let syntaxOk = true;
try { execSync(`python -m py_compile "${appointmentServerPath}"`, { stdio: 'pipe' }); } catch (error) { syntaxOk = false; check('python-syntax-fail', 'python syntax check failed for appointment server', false, 'python -m py_compile failed'); }
const syntaxTargets = [
  appJsPath,
  path.join(netlifyRoot, 'ae-brain-chat.js'),
  path.join(netlifyRoot, 'ae-brain-health.js'),
  path.join(netlifyRoot, 'ae-brain-smoke.js'),
  path.join(netlifyRoot, 'ae-brain-compare.js'),
  path.join(netlifyRoot, 'ae-brain-smoke-reports.js'),
  path.join(netlifyRoot, 'ae-donor-template.js'),
  path.join(netlifyRoot, 'ae-brain-stream.js'),
  path.join(netlifyRoot, 'ae-brains.js'),
  path.join(netlifyRoot, 'ae-usage-summary.js'),
  path.join(netlifyRoot, 'ae-audit-events.js'),
  path.join(netlifyRoot, 'ae-access-users.js'),
  path.join(netlifyRoot, 'ae-clients.js'),
  path.join(netlifyRoot, 'ae-tasks.js'),
  path.join(netlifyRoot, 'ae-threads.js'),
  path.join(netlifyRoot, 'ae-messages.js'),
  path.join(netlifyRoot, 'ae-assignments.js'),
  path.join(netlifyRoot, 'ae-branch-state.js'),
  path.join(netlifyRoot, 'ae-founder-login.js'),
  path.join(netlifyRoot, 'ae-founder-me.js'),
  path.join(netlifyRoot, 'ae-founder-logout.js'),
  path.join(netlifyRoot, '_shared/ae_auth.js'),
  path.join(netlifyRoot, '_shared/ae_donor_template.js'),
  path.join(netlifyRoot, '_shared/ae_brain.js'),
  path.join(netlifyRoot, '_shared/ae_brain_overrides.js'),
  path.join(netlifyRoot, '_shared/ae_roster.js'),
  path.join(netlifyRoot, '_shared/ae_state.js'),
  path.join(netlifyRoot, '_shared/ae_users.js'),
  path.join(netlifyRoot, '_shared/ae_resources.js'),
  path.join(netlifyRoot, '_shared/ae_providers.js'),
  path.join(netlifyRoot, '_shared/neon.js'),
  path.join(netlifyRoot, 'ae-storage-sync.js'),
  path.join(netlifyRoot, 'media-center.js'),
  path.join(netlifyRoot, '_shared/media_center_video.js'),
  path.join(packRoot, 'Branching Apps/AE-Brain-Command-Site-v8-Additive/assets/storage.mjs'),
  path.join(packRoot, 'Branching Apps/Skye-Media-Center-v1/assets/app.js'),
  path.join(packRoot, 'Branching Apps/Skye-Media-Center-v1/assets/artist.js'),
  path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/netlify/functions/printful-ae-bridge-import.js'),
  path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/netlify/functions/printful-ae-bridge-export.js'),
  path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/netlify/functions/printful-ae-bridge-contract.js'),
  path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/netlify/functions/printful-ae-bridge-profitability.js'),
  path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/netlify/functions/printful-ae-bridge-art-packets.js'),
  path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/netlify/functions/printful-ae-bridge-presence.js'),
  path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/netlify/functions/printful-ae-bridge-hardening.js'),
  path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/netlify/functions/printful-ae-bridge-returns.js'),
  path.join(packRoot, 'Branching Apps/Printful-Commerce-Brain-EDM-pass6/netlify/functions/printful-ae-bridge-incidents.js'),
];
for (const target of syntaxTargets) {
  try {
    execSync(`node --check "${target}"`, { stdio: 'pipe' });
  } catch (error) {
    syntaxOk = false;
    check('syntax-fail', `syntax check failed for ${path.basename(target)}`, false, 'node --check failed');
  }
}
check('syntax-gated-smoke', 'syntax-gated smoke exists for ui and server routes', syntaxOk && syntaxTargets.length >= 10, `Syntax targets checked: ${syntaxTargets.length}`);

let passedKeys = new Set(checks.filter(item => item.pass).map(item => item.key).filter(Boolean));
let directiveMd = buildDirectiveMarkdown(source, passedKeys);
fs.writeFileSync(directivePath, directiveMd, 'utf8');
fs.writeFileSync(rootDirectivePath, directiveMd, 'utf8');
check('smoke-proof-generated', 'smoke proof and directives generated', fs.existsSync(directivePath) && fs.existsSync(rootDirectivePath), 'Directive files regenerated from smoke results');

const status = checks.every(item => item.pass);
const md = ['AE BRAIN COMMAND SITE — SMOKE PROOF', '', `Status: ${status ? 'PASS' : 'FAIL'}`, `Run at: ${new Date().toISOString()}`, '', 'Important boundary:', '- PASS here means the additive files, helpers, syntax checks, and local helper flows passed smoke in the zip itself.', '- This is not a claim that live OpenAI keys or a live database are already deployed.', ''];
for (const item of checks) md.push(`- ${item.pass ? 'PASS' : 'FAIL'} — ${item.name}: ${item.detail}`);
fs.writeFileSync(path.join(root, 'docs/SMOKE_PROOF.md'), md.join('\n') + '\n', 'utf8');
passedKeys = new Set(checks.filter(item => item.pass).map(item => item.key).filter(Boolean));
directiveMd = buildDirectiveMarkdown(source, passedKeys);
fs.writeFileSync(directivePath, directiveMd, 'utf8');
fs.writeFileSync(rootDirectivePath, directiveMd, 'utf8');
console.log(JSON.stringify({ status, checks }, null, 2));
if (!status) process.exit(1);
