#!/usr/bin/env python3
from __future__ import annotations

import difflib
import json
import os
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Tuple

from common import (
    copy_tree,
    read_json,
    read_text_safe,
    workspace_paths,
    write_json,
    write_text,
    zip_directory,
)
import scan_zip


def iso_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z')


def write_if_missing(path: Path, content: str, executable: bool = False) -> bool:
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding='utf-8')
    if executable:
        os.chmod(path, 0o755)
    return True


def generate_readme(project_label: str, report: Dict[str, Any]) -> str:
    commands = report.get('commands', {})
    command_lines = '\n'.join(f"- `{key}`: `{value}`" for key, value in commands.items()) or '- No bootstrap commands were confidently detected.'
    frameworks = ', '.join(report.get('frameworks', [])) or 'Unspecified frameworks'
    providers = ', '.join(sorted(report.get('integrations', {}).get('providers', {}).keys())) or 'No providers detected'
    return f"""# {project_label}

This README was generated by the SkyeHands Valuation Certification System patch lab.

## Detected stack

- Frameworks: {frameworks}
- Languages: {', '.join(report.get('languages', {}).get('counts', {}).keys()) or 'Unknown'}
- Providers: {providers}
- Commercial profile: {report.get('commercialProfile', 'founder-core-asset')}

## Launch profiles

{command_lines}

## Runtime proof snapshot

- Runtime status: {report.get('runtimeProof', {}).get('status', 'not-run')}
- Passed checks: {report.get('runtimeProof', {}).get('passedCheckCount', 0)}
- Failed checks: {report.get('runtimeProof', {}).get('failedCheckCount', 0)}

## Certification snapshot

- Overall score: {report.get('valuation', {}).get('overallScore', 0)}/100
- Issued value: ${report.get('valuation', {}).get('values', {}).get('issuedSkyeHandsCertificationValue', 0):,.0f}
- Build floor: ${report.get('valuation', {}).get('values', {}).get('buildFloorValue', 0):,.0f}

## Next actions

- Review the generated SkyeHands directive.
- Run smoke coverage for critical routes and integrations.
- Re-scan after making material code changes.
"""


def generate_env_example(report: Dict[str, Any]) -> str:
    env_vars = report.get('reconstruction', {}).get('envVars', []) or report.get('integrations', {}).get('allEnvVars', [])
    lines = ['# Generated by SkyeHands Valuation Certification System']
    for env in env_vars[:200]:
        lines.append(f'{env}=')
    if len(lines) == 1:
        lines.append('PORT=3000')
    return '\n'.join(lines) + '\n'


def js_smoke_script(report: Dict[str, Any]) -> str:
    static_target = None
    for profile in report.get('reconstruction', {}).get('launchProfiles', []):
        if profile.get('type') == 'static-surface':
            static_target = profile.get('target')
            break
    primary_target = None
    for key in ['smoke', 'test', 'start', 'dev']:
        command = report.get('commands', {}).get(key)
        if command:
            primary_target = scan_zip.resolve_command_target(command, Path('.')).get('target')
            if primary_target:
                break
    target_line = f"const runtimeTarget = path.join(root, {json.dumps(primary_target)});" if primary_target else 'const runtimeTarget = null;'
    static_line = f"const staticTarget = path.join(root, {json.dumps(static_target)});" if static_target else 'const staticTarget = null;'
    return f"""#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
{target_line}
{static_line}

if (runtimeTarget && !fs.existsSync(runtimeTarget)) {{
  console.error(`Missing runtime target: ${{runtimeTarget}}`);
  process.exit(1);
}}

if (staticTarget) {{
  const html = fs.readFileSync(staticTarget, 'utf8');
  if (!/<title>/i.test(html) && !/<!doctype/i.test(html)) {{
    console.error('Static surface missing title or doctype proof.');
    process.exit(1);
  }}
}}

console.log('skyehands smoke ok');
"""


def js_test_file() -> str:
    return """import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

test('package metadata is present', () => {
  assert.equal(fs.existsSync('package.json'), true);
});

test('project has a visible entry surface', () => {
  const hasHtml = fs.existsSync('index.html') || fs.existsSync('public/index.html');
  const hasRuntime = fs.existsSync('server.mjs') || fs.existsSync('server.js') || fs.existsSync('app.py') || fs.existsSync('main.py');
  assert.equal(hasHtml || hasRuntime, true);
});
"""


def py_smoke_script(report: Dict[str, Any]) -> str:
    runtime_target = None
    for key in ['smoke', 'test', 'start', 'dev']:
        command = report.get('commands', {}).get(key)
        if command:
            runtime_target = scan_zip.resolve_command_target(command, Path('.')).get('target')
            if runtime_target:
                break
    return f"""#!/usr/bin/env python3
from pathlib import Path
import sys

root = Path.cwd()
target = root / {json.dumps(runtime_target)} if {json.dumps(bool(runtime_target))} else None
if target and not target.exists():
    print(f'Missing runtime target: {{target}}', file=sys.stderr)
    raise SystemExit(1)
if (root / 'index.html').exists() or (root / 'public' / 'index.html').exists():
    html_path = (root / 'public' / 'index.html') if (root / 'public' / 'index.html').exists() else (root / 'index.html')
    text = html_path.read_text(encoding='utf-8', errors='ignore').lower()
    if '<title>' not in text and '<!doctype' not in text:
        print('Static surface missing title or doctype proof.', file=sys.stderr)
        raise SystemExit(1)
print('skyehands smoke ok')
"""


def py_test_file() -> str:
    return """from pathlib import Path

def test_entry_surface_present():
    root = Path.cwd()
    assert any((root / rel).exists() for rel in ['index.html', 'public/index.html', 'server.mjs', 'server.js', 'app.py', 'main.py'])
"""


def github_workflow(report: Dict[str, Any], is_python: bool) -> str:
    test_cmd = 'python3 -m pytest -q' if is_python else 'node --test'
    smoke_cmd = 'python3 scripts/skyehands_smoke.py' if is_python else 'node scripts/skyehands-smoke.mjs'
    setup = """
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python3 -m pip install --upgrade pip pytest
""" if is_python else """
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
"""
    return f"""name: skyehands-certification
on:
  push:
  pull_request:
jobs:
  smoke-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
{setup.rstrip()}
      - run: {smoke_cmd}
      - run: {test_cmd}
"""


def netlify_config() -> str:
    return """[build]
publish = "public"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
"""




def create_platform_manifest(report: Dict[str, Any]) -> str:
    payload = {
        'version': 1,
        'slug': report.get('platformManifest', {}).get('slug') or report['projectLabel'].lower().replace(' ', '-'),
        'displayName': report['projectLabel'],
        'sourceFingerprint': report.get('fingerprint'),
        'launchProfileCount': len(report.get('reconstruction', {}).get('launchProfiles', [])),
        'readyLaunchProfileCount': len([p for p in report.get('reconstruction', {}).get('launchProfiles', []) if p.get('targetExists')]),
        'smokeProfileCount': len(report.get('reconstruction', {}).get('smokeProfiles', [])),
        'readySmokeProfileCount': report.get('runtimeProof', {}).get('passedCheckCount', 0),
        'capsuleCount': len(report.get('powerMesh', {}).get('capsules', [])),
        'routeTargetCount': report.get('routes', {}).get('routeSignalCount', 0),
        'registeredAt': iso_now(),
    }
    return json.dumps(payload, indent=2) + '\n'


def create_power_mesh_file(report: Dict[str, Any]) -> str:
    payload = {
        'version': 1,
        'platform': report.get('platformManifest', {}).get('slug') or report['projectLabel'].lower().replace(' ', '-'),
        'capsules': report.get('powerMesh', {}).get('capsules', []),
        'envKeyCount': len(report.get('reconstruction', {}).get('envVars', [])),
        'routeTargetCount': report.get('routes', {}).get('routeSignalCount', 0),
        'fingerprint': report.get('powerMesh', {}).get('fingerprint') or report.get('fingerprint'),
        'generatedAt': iso_now(),
    }
    return json.dumps(payload, indent=2) + '\n'


def validation_script(is_python: bool) -> str:
    if is_python:
        return """#!/usr/bin/env python3
from pathlib import Path
import json
root = Path.cwd()
required = ['SKYEHANDS_LAUNCH_MANIFEST.json', 'skyehands.platform.json', 'skyehands.power.json']
missing = [name for name in required if not (root / name).exists()]
if missing:
    raise SystemExit(f'Missing required generated files: {missing}')
print(json.dumps({'ok': True, 'required': required}))
"""
    return """#!/usr/bin/env node
import fs from 'node:fs';
const required = ['SKYEHANDS_LAUNCH_MANIFEST.json', 'skyehands.platform.json', 'skyehands.power.json'];
const missing = required.filter(name => !fs.existsSync(name));
if (missing.length) {
  console.error(`Missing required generated files: ${missing.join(', ')}`);
  process.exit(1);
}
console.log(JSON.stringify({ ok: true, required }));
"""

def create_launch_manifest(source_dir: Path, report: Dict[str, Any]) -> str:
    manifest = {
        'generatedAt': iso_now(),
        'projectLabel': report['projectLabel'],
        'launchProfiles': report.get('reconstruction', {}).get('launchProfiles', []),
        'smokeProfiles': report.get('reconstruction', {}).get('smokeProfiles', []),
        'providers': sorted(report.get('integrations', {}).get('providers', {}).keys()),
    }
    return json.dumps(manifest, indent=2) + '\n'


def ensure_package_json(source_dir: Path, report: Dict[str, Any]) -> Tuple[Path, Dict[str, Any]]:
    package_path = source_dir / 'package.json'
    package_json = read_json(package_path, None)
    if package_json is None:
        package_json = {
            'name': report['projectLabel'].lower().replace(' ', '-'),
            'version': '0.0.1',
            'private': True,
            'scripts': {},
        }
    package_json.setdefault('scripts', {})
    package_path.parent.mkdir(parents=True, exist_ok=True)
    return package_path, package_json


def apply_patches(source_dir: Path, report: Dict[str, Any], patch_request: Dict[str, Any]) -> Tuple[List[Dict[str, Any]], List[Path]]:
    applied: List[Dict[str, Any]] = []
    touched_files: List[Path] = []
    requested = set(patch_request.get('patchIds') or [])
    patch_all = not requested
    issue_ids = {issue['issueId'] for issue in report.get('issues', [])}
    is_python = report.get('reconstruction', {}).get('projectClass', {}).get('primaryRuntime') == 'python'

    def allow(patch_id: str) -> bool:
        return patch_all or patch_id in requested

    def touch(path: Path, patch_id: str, title: str) -> None:
        if path not in touched_files:
            touched_files.append(path)
        applied.append({'patchId': patch_id, 'title': title, 'file': path.relative_to(source_dir).as_posix()})

    if 'missing-readme' in issue_ids and allow('missing-readme'):
        readme_path = source_dir / 'README.md'
        if write_if_missing(readme_path, generate_readme(report['projectLabel'], report)):
            touch(readme_path, 'missing-readme', 'Generated README.md')

    if 'missing-env-example' in issue_ids and allow('missing-env-example'):
        env_example = source_dir / '.env.example'
        if write_if_missing(env_example, generate_env_example(report)):
            touch(env_example, 'missing-env-example', 'Generated .env.example')

    if 'missing-license' in issue_ids and allow('missing-license'):
        license_path = source_dir / 'LICENSE.md'
        if write_if_missing(license_path, '# License Placeholder\n\nReplace this file with the intended license before release.\n'):
            touch(license_path, 'missing-license', 'Generated LICENSE.md placeholder')

    package_path, package_json = ensure_package_json(source_dir, report)
    scripts = package_json.setdefault('scripts', {})
    package_changed = False

    if 'missing-start-script' in issue_ids and allow('missing-start-script'):
        if 'start' not in scripts:
            for candidate in ['server.mjs', 'server.js', 'app.py', 'main.py']:
                if (source_dir / candidate).exists():
                    scripts['start'] = f"{'python3' if candidate.endswith('.py') else 'node'} {candidate}"
                    package_changed = True
                    break
            if (source_dir / 'public' / 'index.html').exists() and 'start' not in scripts:
                scripts['start'] = 'node scripts/skyehands-static-preview.mjs'
                preview_path = source_dir / 'scripts' / 'skyehands-static-preview.mjs'
                if write_if_missing(preview_path, "import http from 'node:http'; import fs from 'node:fs'; const html = fs.readFileSync('public/index.html','utf8'); http.createServer((_,res)=>{res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'}); res.end(html);}).listen(process.env.PORT || 3000); console.log('static preview ready');\n"):
                    touch(preview_path, 'missing-start-script', 'Generated static preview runtime')
        if 'start' in scripts:
            package_changed = True

    if 'missing-smoke-script' in issue_ids and allow('missing-smoke-script'):
        if is_python:
            smoke_script_path = source_dir / 'scripts' / 'skyehands_smoke.py'
            if write_if_missing(smoke_script_path, py_smoke_script(report), executable=True):
                touch(smoke_script_path, 'missing-smoke-script', 'Generated Python smoke script')
            if 'smoke' not in scripts:
                scripts['smoke'] = 'python3 scripts/skyehands_smoke.py'
                package_changed = True
        else:
            smoke_script_path = source_dir / 'scripts' / 'skyehands-smoke.mjs'
            if write_if_missing(smoke_script_path, js_smoke_script(report), executable=True):
                touch(smoke_script_path, 'missing-smoke-script', 'Generated Node smoke script')
            if 'smoke' not in scripts:
                scripts['smoke'] = 'node scripts/skyehands-smoke.mjs'
                package_changed = True

    if 'missing-tests' in issue_ids and allow('missing-tests'):
        if is_python:
            test_path = source_dir / 'tests' / 'test_skyehands_smoke.py'
            if write_if_missing(test_path, py_test_file()):
                touch(test_path, 'missing-tests', 'Generated Python smoke test')
            if 'test' not in scripts:
                scripts['test'] = 'python3 -m pytest -q'
                package_changed = True
        else:
            test_path = source_dir / 'tests' / 'skyehands-smoke.test.mjs'
            if write_if_missing(test_path, js_test_file()):
                touch(test_path, 'missing-tests', 'Generated Node smoke test')
            if 'test' not in scripts:
                scripts['test'] = 'node --test'
                package_changed = True

    if 'missing-ci' in issue_ids and allow('missing-ci'):
        workflow_path = source_dir / '.github' / 'workflows' / 'skyehands-certification.yml'
        if write_if_missing(workflow_path, github_workflow(report, is_python)):
            touch(workflow_path, 'missing-ci', 'Generated GitHub Actions smoke workflow')
        if (source_dir / 'public').exists() or (source_dir / 'index.html').exists():
            netlify_toml = source_dir / 'netlify.toml'
            if write_if_missing(netlify_toml, netlify_config()):
                touch(netlify_toml, 'missing-ci', 'Generated netlify.toml')

    launch_manifest = source_dir / 'SKYEHANDS_LAUNCH_MANIFEST.json'
    launch_manifest.write_text(create_launch_manifest(source_dir, report), encoding='utf-8')
    touch(launch_manifest, 'launch-manifest', 'Generated SKYEHANDS_LAUNCH_MANIFEST.json')

    platform_manifest = source_dir / 'skyehands.platform.json'
    platform_manifest.write_text(create_platform_manifest(report), encoding='utf-8')
    touch(platform_manifest, 'platform-manifest', 'Generated skyehands.platform.json')

    power_mesh_file = source_dir / 'skyehands.power.json'
    power_mesh_file.write_text(create_power_mesh_file(report), encoding='utf-8')
    touch(power_mesh_file, 'power-mesh', 'Generated skyehands.power.json')

    if is_python:
        validator = source_dir / 'scripts' / 'skyehands_validate.py'
        if write_if_missing(validator, validation_script(True), executable=True):
            touch(validator, 'validation-script', 'Generated Python validation script')
        if 'validate' not in scripts:
            scripts['validate'] = 'python3 scripts/skyehands_validate.py'
            package_changed = True
    else:
        validator = source_dir / 'scripts' / 'skyehands-validate.mjs'
        if write_if_missing(validator, validation_script(False), executable=True):
            touch(validator, 'validation-script', 'Generated Node validation script')
        if 'validate' not in scripts:
            scripts['validate'] = 'node scripts/skyehands-validate.mjs'
            package_changed = True

    if package_changed:
        package_path.write_text(json.dumps(package_json, indent=2) + '\n', encoding='utf-8')
        touch(package_path, 'package-json', 'Updated package.json scripts')

    directive_path = source_dir / 'SKYEHANDS_DIRECTIVE.md'
    remaining_titles = {issue['title']: issue for issue in report.get('issues', [])}
    closed_issue_ids = {entry['patchId'] for entry in applied}
    directive_lines = [
        '# SkyeHands Directive',
        '',
        f'Generated: {iso_now()}',
        '',
        '## Applied Lanes',
        '',
    ]
    if applied:
        seen = set()
        for entry in applied:
            line = f"- ✅ {entry['title']}"
            if line not in seen:
                directive_lines.append(line)
                seen.add(line)
    else:
        directive_lines.append('- ⬜ No patchable lanes were applied in this run.')
    directive_lines.extend(['', '## Remaining Lanes', ''])
    for issue in report.get('issues', []):
        if issue['issueId'] in closed_issue_ids:
            continue
        directive_lines.append(f"- ⬜ {issue['title']} — {issue['detail']}")
    if len(directive_lines) <= 9:
        directive_lines.append('- ✅ No remaining patchable lanes in the current scan envelope.')
    directive_path.write_text('\n'.join(directive_lines) + '\n', encoding='utf-8')
    if directive_path not in touched_files:
        touched_files.append(directive_path)
    applied.append({'patchId': 'skyehands-directive', 'title': 'Generated SKYEHANDS_DIRECTIVE.md', 'file': 'SKYEHANDS_DIRECTIVE.md'})

    return applied, touched_files


def build_diff(original_dir: Path, patched_dir: Path, touched_files: List[Path]) -> str:
    segments: List[str] = []
    for patched_path in touched_files:
        rel = patched_path.relative_to(patched_dir).as_posix()
        original_path = original_dir / rel
        patched_text = read_text_safe(patched_path)
        original_text = read_text_safe(original_path) if original_path.exists() else ''
        diff = difflib.unified_diff(
            original_text.splitlines(),
            patched_text.splitlines(),
            fromfile=f'a/{rel}',
            tofile=f'b/{rel}',
            lineterm=''
        )
        rendered = '\n'.join(diff)
        if rendered:
            segments.append(rendered)
    return '\n\n'.join(segments) + ('\n' if segments else '')


def main() -> None:
    if len(sys.argv) < 3:
        raise SystemExit('usage: patch_zip.py <workspace_id> <patch_request_json>')
    workspace_id = sys.argv[1]
    patch_request = json.loads(sys.argv[2]) if sys.argv[2] else {}
    paths = workspace_paths(workspace_id)
    scorecard_path = paths['artifacts'] / 'VCS-004-scorecard.json'
    report = read_json(scorecard_path, None)
    if not report:
        raise SystemExit('missing scan report; import and scan before patching')

    source_dir = paths['runtime'] / 'source'
    patch_dir = paths['runtime'] / 'patched-source'
    copy_tree(source_dir, patch_dir)
    applied, touched_files = apply_patches(patch_dir, report, patch_request)
    diff_text = build_diff(source_dir, patch_dir, touched_files)

    updated_zip = zip_directory(patch_dir, paths['artifacts'] / 'VCS-008-updated-codebase.zip')
    diff_file = write_text(paths['artifacts'] / 'VCS-006-patch.diff', diff_text or '# No textual diff was generated for this patch run.\n')

    temp_metadata = paths['runtime'] / 'patch-metadata.json'
    temp_metadata.write_text(json.dumps({
        'projectLabel': report['projectLabel'],
        'commercialProfile': report.get('commercialProfile', 'founder-core-asset'),
        'autonomyMode': report.get('autonomyMode', 'draft-and-wait'),
        'patchMode': 'patched'
    }, indent=2) + '\n', encoding='utf-8')

    rescanned_result = scan_zip.scan_workspace(workspace_id, updated_zip, read_json(temp_metadata, {}) or {})
    rescanned_report = rescanned_result['report']

    renamed_artifacts = {}
    canonical_map = {
        'VCS-001-intake-dossier.json': 'intakeDossierPatched',
        'VCS-002-reconstruction-binder.json': 'reconstructionBinderPatched',
        'VCS-003-evidence-index.json': 'evidenceIndexPatched',
        'VCS-004-scorecard.json': 'scorecardPatched',
        'VCS-005-exception-register.json': 'exceptionRegisterPatched',
        'VCS-007-certification-sheet.json': 'certificationSheetPatched',
        'VCS-009-skyehands-directive.md': 'directivePatched',
        'VCS-010-audit-surface.html': 'auditSurfacePatched',
        'VCS-011-deep-scan-run.json': 'deepScanRunPatched',
        'VCS-012-environment-mirror.json': 'environmentMirrorPatched',
        'VCS-013-platform-manifest.json': 'platformManifestPatched',
        'VCS-014-power-mesh.json': 'powerMeshPatched',
        'VCS-015-workspace-portfolio.json': 'workspacePortfolioPatched',
        'VCS-016-authority-certificate.json': 'authorityCertificatePatched',
        'VCS-017-authority-verification.json': 'authorityVerificationPatched',
        'VCS-018-council-arbitration.json': 'councilArbitrationPatched',
        'VCS-019-runtime-matrix.json': 'runtimeMatrixPatched',
        'VCS-020-completion-ledger.json': 'completionLedgerPatched',
        'VCS-021-execution-matrix.json': 'executionMatrixPatched',
        'VCS-022-repair-intelligence.json': 'repairIntelligencePatched',
        'VCS-023-public-trust-readiness.json': 'publicTrustReadinessPatched',
        'VCS-024-public-trust-pack.zip': 'publicTrustPackPatched',
    }
    for artifact_name, artifact_key in canonical_map.items():
        source_path = paths['artifacts'] / artifact_name
        if source_path.exists():
            renamed = source_path.with_name(source_path.stem + '-patched' + source_path.suffix)
            shutil.copy2(source_path, renamed)
            renamed_artifacts[artifact_key] = str(renamed)

    patch_lab = {
        'workspaceId': workspace_id,
        'appliedPatchCount': len(applied),
        'appliedPatches': applied,
        'retestedAt': iso_now(),
        'textDiffGenerated': bool(diff_text.strip()),
        'updatedCodebaseZip': str(updated_zip),
        'diffFile': str(diff_file),
        'issuedValueBefore': report['valuation']['values']['issuedSkyeHandsCertificationValue'],
        'issuedValueAfter': rescanned_report['valuation']['values']['issuedSkyeHandsCertificationValue'],
        'issuedValueDelta': round(rescanned_report['valuation']['values']['issuedSkyeHandsCertificationValue'] - report['valuation']['values']['issuedSkyeHandsCertificationValue'], 2),
        'overallScoreBefore': report['valuation']['overallScore'],
        'overallScoreAfter': rescanned_report['valuation']['overallScore'],
        'overallScoreDelta': round(rescanned_report['valuation']['overallScore'] - report['valuation']['overallScore'], 1),
    }
    patch_report_file = write_json(paths['artifacts'] / 'VCS-006-patch-lab-report.json', patch_lab)

    print(json.dumps({
        'ok': True,
        'report': rescanned_report,
        'patchLab': patch_lab,
        'artifacts': {
            'updatedCodebaseZip': str(updated_zip),
            'patchDiff': str(diff_file),
            'patchLabReport': str(patch_report_file),
            **renamed_artifacts,
        }
    }, indent=2))


if __name__ == '__main__':
    main()
