import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';

const BEGIN = '<!-- SKYDEXIA_MEMORY_CONTEXT_BEGIN -->';
const END = '<!-- SKYDEXIA_MEMORY_CONTEXT_END -->';

export function id(prefix='mem'){return `${prefix}_${new Date().toISOString().replace(/[-:.TZ]/g,'').slice(0,14)}_${crypto.randomBytes(5).toString('hex')}`;}
export function now(){return new Date().toISOString();}
export function tags(input){return Array.isArray(input)?input.map(String).filter(Boolean):String(input||'').split(',').map(x=>x.trim()).filter(Boolean);}
export function redactSecrets(input){
  let s = input == null ? '' : (typeof input === 'string' ? input : JSON.stringify(input));
  return s
    .replace(/sk-[A-Za-z0-9_-]{16,}/g,'sk-[REDACTED]')
    .replace(/AIza[0-9A-Za-z_-]{20,}/g,'AIza[REDACTED]')
    .replace(/ghp_[0-9A-Za-z_]{20,}/g,'ghp_[REDACTED]')
    .replace(/github_pat_[0-9A-Za-z_]{20,}/g,'github_pat_[REDACTED]')
    .replace(/(api[_-]?key|secret|token|password|passwd|pwd)\s*[:=]\s*['"]?[^\s'"]+/gi,'$1=[REDACTED]')
    .replace(/(Bearer\s+)[A-Za-z0-9._-]{16,}/g,'$1[REDACTED]');
}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function toks(s){return norm(s).split(/\s+/).filter(x=>x.length>1);}
function memText(m){return [m.title,m.type,...(m.tags||[]),m.text,JSON.stringify(m.evidence||{})].join(' ');}
async function mkdirp(dir){await fs.mkdir(dir,{recursive:true});}
async function readJsonl(file){try{return (await fs.readFile(file,'utf8')).split(/\r?\n/).filter(Boolean).map(JSON.parse);}catch(e){if(e.code==='ENOENT')return [];throw e;}}
async function appendJsonl(file,obj){await fs.appendFile(file,JSON.stringify(obj)+'\n','utf8');}

export class LocalJsonlStore{
  constructor(o={}){this.rootDir=o.rootDir||path.join(process.cwd(),'.skydexia-memory');this.memoryFile=path.join(this.rootDir,'memory.jsonl');this.eventFile=path.join(this.rootDir,'events.jsonl');this.configFile=path.join(this.rootDir,'config.json');}
  async init(config={}){await mkdirp(this.rootDir);await mkdirp(path.join(this.rootDir,'exports'));try{await fs.access(this.configFile);}catch{await fs.writeFile(this.configFile,JSON.stringify({createdAt:now(),...config},null,2)+'\n');}}
  async appendMemory(m){await this.init();await appendJsonl(this.memoryFile,m);return m;}
  async appendEvent(e){await this.init();await appendJsonl(this.eventFile,e);return e;}
  async listMemories(f={}){await this.init();return (await readJsonl(this.memoryFile)).filter(m=>(!f.projectId||m.projectId===f.projectId)&&(!f.actorId||m.actorId===f.actorId));}
  async listEvents(f={}){await this.init();return (await readJsonl(this.eventFile)).filter(e=>(!f.projectId||e.projectId===f.projectId)&&(!f.actorId||e.actorId===f.actorId));}
}
export class MemoryStore{constructor(){this.memories=[];this.events=[];}async init(){}async appendMemory(m){this.memories.push(m);return m;}async appendEvent(e){this.events.push(e);return e;}async listMemories(f={}){return this.memories.filter(m=>(!f.projectId||m.projectId===f.projectId));}async listEvents(f={}){return this.events.filter(e=>(!f.projectId||e.projectId===f.projectId));}}
export class CloudflareD1Store{constructor(o={}){if(!o.db)throw new Error('CloudflareD1Store requires options.db D1 binding');this.db=o.db;}async init(){await this.db.prepare('CREATE TABLE IF NOT EXISTS skydexia_memories (id TEXT PRIMARY KEY, payload TEXT NOT NULL, project_id TEXT NOT NULL, created_at TEXT NOT NULL)').run();await this.db.prepare('CREATE TABLE IF NOT EXISTS skydexia_memory_events (id TEXT PRIMARY KEY, payload TEXT NOT NULL, project_id TEXT NOT NULL, created_at TEXT NOT NULL)').run();}async appendMemory(m){await this.init();await this.db.prepare('INSERT INTO skydexia_memories (id,payload,project_id,created_at) VALUES (?,?,?,?)').bind(m.id,JSON.stringify(m),m.projectId,m.createdAt).run();return m;}async appendEvent(e){await this.init();await this.db.prepare('INSERT INTO skydexia_memory_events (id,payload,project_id,created_at) VALUES (?,?,?,?)').bind(e.id,JSON.stringify(e),e.projectId,e.createdAt).run();return e;}async listMemories(f={}){await this.init();const q=f.projectId?this.db.prepare('SELECT payload FROM skydexia_memories WHERE project_id=? ORDER BY created_at DESC').bind(f.projectId):this.db.prepare('SELECT payload FROM skydexia_memories ORDER BY created_at DESC');const r=await q.all();return (r.results||[]).map(x=>JSON.parse(x.payload));}async listEvents(f={}){await this.init();const q=f.projectId?this.db.prepare('SELECT payload FROM skydexia_memory_events WHERE project_id=? ORDER BY created_at DESC').bind(f.projectId):this.db.prepare('SELECT payload FROM skydexia_memory_events ORDER BY created_at DESC');const r=await q.all();return (r.results||[]).map(x=>JSON.parse(x.payload));}}
export class NeonPostgresStore{constructor(o={}){this.connectionString=o.connectionString||process.env.DATABASE_URL||process.env.NEON_DATABASE_URL;this.pool=o.pool;if(!this.connectionString&&!this.pool)throw new Error('NeonPostgresStore requires connectionString, pool, DATABASE_URL, or NEON_DATABASE_URL');}async getPool(){if(this.pool)return this.pool;const pg=await import('pg');this.pool=new pg.Pool({connectionString:this.connectionString});return this.pool;}async init(){const p=await this.getPool();await p.query('CREATE TABLE IF NOT EXISTS skydexia_memories (id text PRIMARY KEY, payload jsonb NOT NULL, project_id text NOT NULL, created_at timestamptz NOT NULL)');await p.query('CREATE TABLE IF NOT EXISTS skydexia_memory_events (id text PRIMARY KEY, payload jsonb NOT NULL, project_id text NOT NULL, created_at timestamptz NOT NULL)');}async appendMemory(m){await this.init();await (await this.getPool()).query('INSERT INTO skydexia_memories (id,payload,project_id,created_at) VALUES ($1,$2,$3,$4)',[m.id,m,m.projectId,m.createdAt]);return m;}async appendEvent(e){await this.init();await (await this.getPool()).query('INSERT INTO skydexia_memory_events (id,payload,project_id,created_at) VALUES ($1,$2,$3,$4)',[e.id,e,e.projectId,e.createdAt]);return e;}async listMemories(f={}){await this.init();const p=await this.getPool();const r=f.projectId?await p.query('SELECT payload FROM skydexia_memories WHERE project_id=$1 ORDER BY created_at DESC',[f.projectId]):await p.query('SELECT payload FROM skydexia_memories ORDER BY created_at DESC');return r.rows.map(x=>x.payload);}async listEvents(f={}){await this.init();const p=await this.getPool();const r=f.projectId?await p.query('SELECT payload FROM skydexia_memory_events WHERE project_id=$1 ORDER BY created_at DESC',[f.projectId]):await p.query('SELECT payload FROM skydexia_memory_events ORDER BY created_at DESC');return r.rows.map(x=>x.payload);}}

function makeStore(storage={}){if(storage.kind==='memory')return new MemoryStore();if(storage.kind==='cloudflare-d1')return new CloudflareD1Store(storage);if(storage.kind==='neon-postgres')return new NeonPostgresStore(storage);return new LocalJsonlStore(storage);}
export function scoreMemories(memories,query='',o={}){const qs=new Set(toks(query));return memories.filter(m=>!(o.includeDirectives===false&&m.type==='directive')&&!(o.includeSmokeProof===false&&m.type==='smoke-proof')&&!(o.includeFailures===false&&m.type==='failure')).map(m=>{const body=norm(memText(m));const ms=new Set(toks(body));let s=0;for(const q of qs)if(ms.has(q))s++;if(qs.size>1&&body.includes(norm(query)))s+=5;if((m.tags||[]).some(t=>qs.has(norm(t))))s+=2;return {memory:m,score:s};}).filter(x=>x.score>0||qs.size===0).sort((a,b)=>b.score-a.score||String(b.memory.createdAt).localeCompare(String(a.memory.createdAt)));}
export function buildContextText(scored,{limit=8}={}){const rows=scored.slice(0,limit).map(x=>x.memory||x);if(!rows.length)return 'SkyDexia Memory Fabric: no matching memories found.';return rows.map((m,i)=>`Memory ${i+1}: ${m.title}\nType: ${m.type}\nTags: ${(m.tags||[]).join(', ')||'none'}\nCreated: ${m.createdAt}\nText: ${m.text}${m.evidence&&Object.keys(m.evidence).length?`\nEvidence: ${JSON.stringify(m.evidence)}`:''}`).join('\n\n---\n\n');}
export async function injectContextBlock({target='AGENTS.md',contextText,heading='SkyDexia Memory Context',mode='replace-block'}={}){const file=path.resolve(process.cwd(),target);let old='';try{old=await fs.readFile(file,'utf8');}catch(e){if(e.code!=='ENOENT')throw e;}const block=`${BEGIN}\n# ${heading}\n\n${contextText}\n${END}\n`;let next;if(old.includes(BEGIN)&&old.includes(END))next=old.replace(new RegExp(`${BEGIN}[\\s\\S]*?${END}\\n?`,'m'),block);else next=mode==='prepend'?block+'\n'+old:(old?old.replace(/\s*$/,'')+'\n\n'+block:block);await mkdirp(path.dirname(file));await fs.writeFile(file,next,'utf8');return {target:file,inserted:true,bytes:Buffer.byteLength(next)};}
export function createSkyDexiaMemory(o={}){const mode=o.mode||'local-sidecar', projectId=o.projectId||'default-project', actorId=o.actorId||'skydexia', proofMode=o.proofMode!==false, store=o.store||makeStore(o.storage||{kind:'local-jsonl',rootDir:o.rootDir});
  async function init(){await store.init({mode,projectId,actorId,proofMode});await store.appendEvent({id:id('evt'),projectId,actorId,type:'memory_fabric_initialized',payload:{mode,proofMode},createdAt:now()});}
  async function remember(input={}){if(!input.title&&!input.text)throw new Error('remember requires title or text');const m={id:input.id||id('mem'),projectId:input.projectId||projectId,actorId:input.actorId||actorId,mode,type:input.type||'note',title:redactSecrets(input.title||String(input.text||'').slice(0,80)),tags:tags(input.tags||input.tag),text:redactSecrets(input.text||''),evidence:input.evidence?JSON.parse(redactSecrets(input.evidence)):{},createdAt:input.createdAt||now()};await store.appendMemory(m);await store.appendEvent({id:id('evt'),projectId:m.projectId,actorId:m.actorId,type:'memory_recorded',payload:{memoryId:m.id,memoryType:m.type,title:m.title},createdAt:now()});return m;}
  async function recall(input={}){const query=typeof input==='string'?input:input.query||'', opts=typeof input==='string'?{}:input;const memories=await store.listMemories({projectId:opts.projectId||projectId});const scored=scoreMemories(memories,query,opts);const limit=Number(opts.limit||8);return {query,count:Math.min(scored.length,limit),results:scored.slice(0,limit).map(x=>({...x.memory,score:x.score})),contextText:buildContextText(scored,{limit})};}
  async function inject(input={}){const r=await recall({...input,query:input.query||''});const out=await injectContextBlock({target:input.target||'AGENTS.md',contextText:r.contextText,heading:input.heading||'SkyDexia Memory Context'});await store.appendEvent({id:id('evt'),projectId,actorId,type:'context_injected',payload:{target:out.target,query:input.query||'',memoryCount:r.count},createdAt:now()});return {...out,recalled:r};}
  async function rememberDirectiveStatus(d={}){return remember({type:'directive',title:d.title||'Directive status',tags:['directive',d.complete?'complete':'open',...tags(d.tags)],text:d.text||'',evidence:{complete:Boolean(d.complete),...(d.evidence||{})}});}
  async function rememberSmokeProof(s={}){return remember({type:s.passed?'smoke-proof':'failure',title:s.title||(s.passed?'Smoke proof passed':'Smoke proof failed'),tags:['smoke',s.passed?'proof':'failure',...tags(s.tags)],text:s.text||'',evidence:{passed:Boolean(s.passed),...(s.evidence||{})}});}
  async function exportPack(){return {version:'6.8.1',exportedAt:now(),mode,projectId,actorId,memories:await store.listMemories({projectId}),events:await store.listEvents({projectId})};}
  return {version:'6.8.1',mode,projectId,actorId,proofMode,store,init,remember,recall,inject,rememberDirectiveStatus,rememberSmokeProof,exportPack};}
